import {useCallback,useEffect,useState} from "react";
import type {ApiClient,CoachAssignment} from "../../services/apiClient";

export function CoachAssignmentsPage({client}:{client:ApiClient}){
 const [coaches,setCoaches]=useState<{user_id:string;display_name:string;email:string}[]>([]),[athletes,setAthletes]=useState<{athlete_profile_id:string;display_name:string}[]>([]),[items,setItems]=useState<CoachAssignment[]>([]),[coach,setCoach]=useState(""),[athlete,setAthlete]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{if(!client.coachAssignmentCandidates||!client.coachAssignments)throw new Error();const [c,a]=await Promise.all([client.coachAssignmentCandidates(),client.coachAssignments()]);setCoaches(c.coaches);setAthletes(c.athletes);setItems(a);setCoach(v=>v||c.coaches[0]?.user_id||"");setAthlete(v=>v||c.athletes[0]?.athlete_profile_id||"")}catch{setError("No se han podido cargar los entrenadores.")}finally{setLoading(false)}},[client]);
 useEffect(()=>{void load()},[load]);
 async function assign(){if(!coach||!athlete||!client.createCoachAssignment)return;setBusy(true);setError("");try{await client.createCoachAssignment({coach_user_id:coach,athlete_profile_id:athlete});await load()}catch{setError("No se ha podido asignar el entrenador.")}finally{setBusy(false)}}
 async function revoke(item:CoachAssignment){if(!client.revokeCoachAssignment||!window.confirm(`¿Quitar a ${item.coach_display_name} el acceso a ${item.athlete_display_name}?`))return;setBusy(true);setError("");try{await client.revokeCoachAssignment(item.membership_id);await load()}catch{setError("No se ha podido quitar el acceso.")}finally{setBusy(false)}}
 return <section><h1>Entrenadores</h1>{error&&<div role="alert" className="error-banner"><p>{error}</p><button type="button" onClick={()=>void load()}>Reintentar</button></div>}{loading?<p role="status">Cargando entrenadores…</p>:<><section className="form-card"><h2>Asignar entrenador</h2>{!coaches.length?<p>Todavía no hay entrenadores registrados.</p>:<><label htmlFor="coach-candidate">Entrenador</label><select id="coach-candidate" value={coach} onChange={e=>setCoach(e.target.value)}>{coaches.map(x=><option value={x.user_id} key={x.user_id}>{x.display_name} · {x.email}</option>)}</select><label htmlFor="athlete-candidate">Atleta</label><select id="athlete-candidate" value={athlete} onChange={e=>setAthlete(e.target.value)}>{athletes.map(x=><option value={x.athlete_profile_id} key={x.athlete_profile_id}>{x.display_name}</option>)}</select><button className="button button--primary" type="button" disabled={busy||!athletes.length} onClick={()=>void assign()}>Asignar entrenador</button></>}</section><section><h2>Asignaciones activas</h2>{!items.length?<p>Todavía no hay asignaciones activas.</p>:<div className="table-scroll"><table><thead><tr><th>Entrenador</th><th>Atleta</th><th>Acción</th></tr></thead><tbody>{items.map(item=><tr key={item.membership_id}><td>{item.coach_display_name}<small>{item.coach_email}</small></td><td>{item.athlete_display_name}</td><td><button type="button" disabled={busy} onClick={()=>void revoke(item)}>Quitar acceso</button></td></tr>)}</tbody></table></div>}</section></>}</section>
}
