import type { Consistency, DashboardSummary, SportBreakdown, WeeklyTrend } from "../../types/api";
import { formatDate, formatDistance, formatDuration, formatElevation, sportIcon } from "../../utils/format";
import { WeeklyTrendChart } from "./WeeklyTrendChart";
const sportLabels:Record<string,string>={running:"Carrera",cycling:"Ciclismo",swimming:"Natación",other:"Otros"};
export function AthleteOverview({summary,trends,consistency,loading,error,onRetry}:{summary:DashboardSummary|null;trends:WeeklyTrend[];consistency:Consistency|null;loading:boolean;error:string|null;onRetry():void}) {
 if(loading)return <section className="analytics-state" aria-live="polite"><span className="spinner" aria-hidden="true"/><p>Cargando resumen de entrenamiento…</p></section>;
 if(error)return <section className="analytics-state analytics-error" role="alert"><p>{error}</p><button className="button button--secondary" type="button" onClick={onRetry}>Reintentar resumen</button></section>;
 if(!summary||!consistency)return null;
 const bySport=(sport:string):SportBreakdown=>summary.sport_breakdown.find(x=>x.sport_type===sport)??{sport_type:sport,activity_count:0,moving_time_seconds:0,distance_metres:0,elevation_metres:0};
 const averageTime=summary.activity_count?summary.total_moving_time_seconds/summary.activity_count:0,averageDistance=summary.activity_count?summary.total_distance_metres/summary.activity_count:0;
 return <div className="athlete-overview"><section aria-labelledby="week-title"><div className="section-title"><p className="eyebrow">Resumen del atleta</p><h2 id="week-title">Esta semana</h2></div><dl className="week-summary"><div><dt>Entrenamientos</dt><dd>{summary.activity_count}</dd></div><div><dt>Tiempo total</dt><dd>{formatDuration(summary.total_moving_time_seconds)}</dd></div><div><dt>Distancia total</dt><dd>{formatDistance(summary.total_distance_metres)}</dd></div><div><dt>Desnivel total</dt><dd>{formatElevation(summary.total_elevation_metres)}</dd></div><div><dt>Días activos</dt><dd>{summary.active_days}</dd></div><div><dt>Media por actividad</dt><dd>{formatDuration(Math.round(averageTime))}</dd></div><div><dt>Distancia media</dt><dd>{formatDistance(averageDistance)}</dd></div></dl></section><section aria-labelledby="sports-title"><h2 id="sports-title">Resumen por deporte</h2><div className="sport-summary-grid">{["running","cycling","swimming","other"].map(s=>{const x=bySport(s);return <article className="analytics-card sport-summary" key={s}><h3><span aria-hidden="true">{sportIcon(s)} </span>{sportLabels[s]}</h3><p>{x.activity_count} actividades</p><dl><div><dt>Distancia</dt><dd>{formatDistance(x.distance_metres,s)}</dd></div><div><dt>Tiempo</dt><dd>{formatDuration(x.moving_time_seconds)}</dd></div></dl></article>})}</div></section><WeeklyTrendChart items={trends}/><section className="analytics-card consistency" aria-labelledby="consistency-title"><h2 id="consistency-title">Consistencia</h2><dl><div><dt>Semanas activas</dt><dd>{consistency.active_weeks} de {consistency.weeks}</dd></div><div><dt>Racha actual</dt><dd>{consistency.current_training_streak_weeks} semanas</dd></div><div><dt>Mejor racha</dt><dd>{consistency.longest_training_streak_weeks} semanas</dd></div><div><dt>Media de días activos por semana</dt><dd>{consistency.average_active_days_per_week.toLocaleString("es-ES",{maximumFractionDigits:1})}</dd></div><div><dt>Última actividad</dt><dd>{formatDate(consistency.last_activity_at)}</dd></div></dl></section></div>;
}
