import { useEffect, useRef, useState } from "react";
import { DashboardPage } from "../features/dashboard/DashboardPage";
import { ActivitiesPage } from "../features/activities/ActivitiesPage";
import { ActivitySummaryPage } from "../features/activities/ActivitySummaryPage";
import { ActivitySyncButton } from "../components/ActivitySyncButton";
import { apiClient } from "../services/apiClient";
import type { ApiClient } from "../services/apiClient";
import { AppLink, navigate, usePathname } from "./usePathname";
import { useTheme } from "./ThemeProvider";
import { ComingSoonPage } from "./ComingSoonPage";
const nav=[{path:"/dashboard",label:"Inicio",icon:"⌂"},{path:"/activities",label:"Actividades",icon:"▦"},{path:"/calendar",label:"Calendario",icon:"□"},{path:"/statistics",label:"Estadísticas",icon:"◒"},{path:"/health",label:"Salud",icon:"♡"},{path:"/settings",label:"Configuración",icon:"⚙"}];
function greeting(){const hour=new Date().getHours();return hour<12?"Buenos días":hour<20?"Buenas tardes":"Buenas noches";}
function content(path:string){if(path==="/dashboard")return <DashboardPage showSync={false}/>;if(path==="/activities")return <ActivitiesPage/>;if(path.startsWith("/activities/"))return <ActivitySummaryPage activityId={path.slice("/activities/".length)}/>;const match=nav.find(x=>x.path===path);return <ComingSoonPage title={match?.label??"Página"}/>}
export function AppShell({client=apiClient}:{client?:ApiClient}){const [path]=usePathname();const {theme,toggle}=useTheme();const [drawer,setDrawer]=useState(false),[userOpen,setUserOpen]=useState(false);const menuRef=useRef<HTMLDivElement>(null);useEffect(()=>{if(path==="/")navigate("/dashboard")},[path]);useEffect(()=>{setDrawer(false)},[path]);useEffect(()=>{const close=(e:MouseEvent)=>{if(!menuRef.current?.contains(e.target as Node))setUserOpen(false)};document.addEventListener("mousedown",close);return()=>document.removeEventListener("mousedown",close)},[]);const date=new Intl.DateTimeFormat("es-ES",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());return <div className="application-shell"><a className="skip-link" href="#main-content">Saltar al contenido principal</a><aside className={`sidebar ${drawer?"sidebar--open":""}`} aria-label="Navegación principal"><div className="brand"><span className="brand__mark" aria-hidden="true">T</span><span>TriCoach AI</span></div><nav>{nav.map(item=><AppLink key={item.path} to={item.path} className={`nav-link ${(path===item.path||(item.path==="/activities"&&path.startsWith("/activities/")))?"nav-link--active":""}`}><span aria-hidden="true">{item.icon}</span>{item.label}</AppLink>)}</nav><p className="sidebar__version">Versión 0.5B</p></aside>{drawer&&<button className="drawer-backdrop" aria-label="Cerrar navegación" onClick={()=>setDrawer(false)}/>}<div className="application-main"><header className="topbar"><button className="icon-button mobile-menu" type="button" aria-label={drawer?"Cerrar menú":"Abrir menú"} aria-expanded={drawer} onClick={()=>setDrawer(x=>!x)}>☰</button><ActivitySyncButton client={client}/><div className="topbar__greeting"><strong>{greeting()}, Carlos</strong><span>{date}</span></div><div className="topbar__actions"><button className="icon-button" type="button" aria-label={`Activar tema ${theme==="light"?"oscuro":"claro"}`} onClick={toggle}>{theme==="light"?"☾":"☀"}</button><div className="user-menu" ref={menuRef}><button className="user-button" type="button" aria-haspopup="menu" aria-expanded={userOpen} onClick={()=>setUserOpen(x=>!x)}><span className="avatar" aria-hidden="true">C</span><span>Carlos</span><span aria-hidden="true">⌄</span></button>{userOpen&&<div className="user-menu__panel" role="menu"><button role="menuitem" disabled>Perfil <small>Próximamente</small></button><AppLink to="/settings" className="user-menu__link">Configuración</AppLink><button role="menuitem" disabled>Cerrar sesión <small>Desarrollo</small></button></div>}</div></div></header><main id="main-content" className="page-content" tabIndex={-1}>{path==="/"?null:content(path)}</main></div></div>}