import {StrictMode} from "react";import {render,screen,waitFor} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {beforeEach,describe,expect,it,vi} from "vitest";
import type {ApiClient} from "../services/apiClient";import {athleteStorageKey} from "../types/sessionContext";import {AthleteContextProvider,useAthleteContext} from "./AthleteContext";import {AthleteSelector} from "./AthleteSelector";
const athlete=(id:string,label:string,role="owner",is_default=false)=>({athlete_id:id,label,role,is_default,capabilities:["read_athlete_data"] as any});
const context=(athletes:any[],selected:string|null=null,required=false)=>({user:{id:"user-1",display_name:"Ana",email:null},athletes,selected_athlete_id:selected,selection_required:required});
function Probe(){const value=useAthleteContext();return <><span>{value.error?"Error al cargar el contexto":value.loading?"loading":value.activeAthlete?.label??(value.selectionRequired?"required":"none")}</span>{value.error&&<span>{value.error}</span>}<span>{value.role}</span><button onClick={()=>void value.refreshContext({preferredAthleteId:"b"})}>refresh-b</button>{value.athletes.length>1&&<AthleteSelector required={value.selectionRequired}/>}</>}
function renderContext(value:any){const client={sessionContext:vi.fn().mockResolvedValue(value)} as unknown as ApiClient;return {client,...render(<AthleteContextProvider client={client}><Probe/></AthleteContextProvider>)}}
beforeEach(()=>localStorage.clear());
describe("AthleteContextProvider",()=>{
 it("bootstraps one athlete before exposing sports context",async()=>{const {client}=renderContext(context([athlete("a","Mi atleta")],"a"));expect(screen.getByText("loading")).toBeInTheDocument();expect(await screen.findByText("Mi atleta")).toBeInTheDocument();expect(client.sessionContext).toHaveBeenCalledTimes(1)});
 it("uses a valid persisted selection scoped by user",async()=>{localStorage.setItem(athleteStorageKey("user-1"),"b");renderContext(context([athlete("a","Atleta A",undefined,true),athlete("b","Atleta B")],"a"));expect(await screen.findByText("Atleta B")).toBeInTheDocument()});
 it("removes a revoked selection and uses the backend default",async()=>{localStorage.setItem(athleteStorageKey("user-1"),"revoked");renderContext(context([athlete("a","Atleta A",undefined,true)],"a"));await screen.findByText("Atleta A");expect(localStorage.getItem(athleteStorageKey("user-1"))).toBeNull()});
 it("requires an explicit accessible selection and persists it",async()=>{renderContext(context([athlete("a","Atleta A","viewer"),athlete("b","Atleta B","coach")],null,true));const select=await screen.findByRole("combobox",{name:"Seleccionar atleta"});expect(screen.getByText("required")).toBeInTheDocument();await userEvent.selectOptions(select,"b");await waitFor(()=>expect(screen.getByText("Atleta B")).toBeInTheDocument());expect(localStorage.getItem(athleteStorageKey("user-1"))).toBe("b")});
 it("shows no-athlete and context-error states",async()=>{const {unmount}=renderContext(context([]));expect(await screen.findByText("none")).toBeInTheDocument();unmount();const client={sessionContext:vi.fn().mockRejectedValue(new Error())} as unknown as ApiClient;render(<AthleteContextProvider client={client}><Probe/></AthleteContextProvider>);expect(await screen.findByText("Error al cargar el contexto")).toBeInTheDocument();expect(screen.getByText("No se ha podido cargar el contexto de usuario.")).toBeInTheDocument()}); it("ignores StrictMode cleanup cancellation and keeps the later successful context",async()=>{let rejectFirst!:(reason:unknown)=>void,resolveSecond!:(value:any)=>void;const first=new Promise((_,reject)=>{rejectFirst=reject}),second=new Promise(resolve=>{resolveSecond=resolve});const client={sessionContext:vi.fn().mockReturnValueOnce(first).mockReturnValueOnce(second)} as unknown as ApiClient;render(<StrictMode><AthleteContextProvider client={client}><Probe/></AthleteContextProvider></StrictMode>);await waitFor(()=>expect(client.sessionContext).toHaveBeenCalledTimes(2));rejectFirst(new DOMException("cleanup","AbortError"));resolveSecond(context([athlete("a","Mi atleta")],"a"));expect(await screen.findByText("Mi atleta")).toBeInTheDocument();expect(screen.queryByText("Error al cargar el contexto")).not.toBeInTheDocument();expect(screen.queryByText("No se ha podido cargar el contexto de usuario.")).not.toBeInTheDocument()});
 it("still reports a real session context HTTP failure in StrictMode",async()=>{const client={sessionContext:vi.fn().mockRejectedValue(new Error("TriCoach API request failed (500)"))} as unknown as ApiClient;render(<StrictMode><AthleteContextProvider client={client}><Probe/></AthleteContextProvider></StrictMode>);expect(await screen.findByText("Error al cargar el contexto")).toBeInTheDocument();expect(screen.getByText("No se ha podido cargar el contexto de usuario.")).toBeInTheDocument()});
 it("refreshes, immediately selects and persists a newly available preferred athlete",async()=>{const client={sessionContext:vi.fn().mockResolvedValueOnce(context([athlete("a","Atleta A",undefined,true)],"a")).mockResolvedValueOnce(context([athlete("a","Atleta A",undefined,true),athlete("b","Atleta B")],"a"))} as unknown as ApiClient;render(<AthleteContextProvider client={client}><Probe/></AthleteContextProvider>);await screen.findByText("Atleta A");await userEvent.click(screen.getByRole("button",{name:"refresh-b"}));expect(await screen.findByText("Atleta B")).toBeInTheDocument();expect(localStorage.getItem(athleteStorageKey("user-1"))).toBe("b");expect(client.sessionContext).toHaveBeenCalledTimes(2)});
 it("preserves A and does not persist B when the preferred athlete is absent",async()=>{const value=context([athlete("a","Atleta A",undefined,true)],"a"),client={sessionContext:vi.fn().mockResolvedValue(value)} as unknown as ApiClient;render(<AthleteContextProvider client={client}><Probe/></AthleteContextProvider>);await screen.findByText("Atleta A");await userEvent.click(screen.getByRole("button",{name:"refresh-b"}));await waitFor(()=>expect(client.sessionContext).toHaveBeenCalledTimes(2));expect(screen.getByText("Atleta A")).toBeInTheDocument();expect(localStorage.getItem(athleteStorageKey("user-1"))).not.toBe("b")});});
