import {render,screen,waitFor} from "@testing-library/react";import userEvent from "@testing-library/user-event";import {beforeEach,describe,expect,it,vi} from "vitest";
import type {ApiClient} from "../services/apiClient";import {athleteStorageKey} from "../types/sessionContext";import {AthleteContextProvider,useAthleteContext} from "./AthleteContext";import {AthleteSelector} from "./AthleteSelector";
const athlete=(id:string,label:string,role="owner",is_default=false)=>({athlete_id:id,label,role,is_default,capabilities:["read_athlete_data"] as any});
const context=(athletes:any[],selected:string|null=null,required=false)=>({user:{id:"user-1",display_name:"Ana",email:null},athletes,selected_athlete_id:selected,selection_required:required});
function Probe(){const value=useAthleteContext();return <><span>{value.loading?"loading":value.activeAthlete?.label??(value.selectionRequired?"required":"none")}</span><span>{value.role}</span>{value.athletes.length>1&&<AthleteSelector required={value.selectionRequired}/>}</>}
function renderContext(value:any){const client={sessionContext:vi.fn().mockResolvedValue(value)} as unknown as ApiClient;return {client,...render(<AthleteContextProvider client={client}><Probe/></AthleteContextProvider>)}}
beforeEach(()=>localStorage.clear());
describe("AthleteContextProvider",()=>{
 it("bootstraps one athlete before exposing sports context",async()=>{const {client}=renderContext(context([athlete("a","Mi atleta")],"a"));expect(screen.getByText("loading")).toBeInTheDocument();expect(await screen.findByText("Mi atleta")).toBeInTheDocument();expect(client.sessionContext).toHaveBeenCalledTimes(1)});
 it("uses a valid persisted selection scoped by user",async()=>{localStorage.setItem(athleteStorageKey("user-1"),"b");renderContext(context([athlete("a","Atleta A",undefined,true),athlete("b","Atleta B")],"a"));expect(await screen.findByText("Atleta B")).toBeInTheDocument()});
 it("removes a revoked selection and uses the backend default",async()=>{localStorage.setItem(athleteStorageKey("user-1"),"revoked");renderContext(context([athlete("a","Atleta A",undefined,true)],"a"));await screen.findByText("Atleta A");expect(localStorage.getItem(athleteStorageKey("user-1"))).toBeNull()});
 it("requires an explicit accessible selection and persists it",async()=>{renderContext(context([athlete("a","Atleta A","viewer"),athlete("b","Atleta B","coach")],null,true));const select=await screen.findByRole("combobox",{name:"Seleccionar atleta"});expect(screen.getByText("required")).toBeInTheDocument();await userEvent.selectOptions(select,"b");await waitFor(()=>expect(screen.getByText("Atleta B")).toBeInTheDocument());expect(localStorage.getItem(athleteStorageKey("user-1"))).toBe("b")});
 it("shows no-athlete and context-error states",async()=>{const {unmount}=renderContext(context([]));expect(await screen.findByText("none")).toBeInTheDocument();unmount();const client={sessionContext:vi.fn().mockRejectedValue(new Error())} as unknown as ApiClient;render(<AthleteContextProvider client={client}><Probe/></AthleteContextProvider>);await waitFor(()=>expect(screen.getByText("none")).toBeInTheDocument())});
});
