import {act,render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {beforeEach,describe,expect,it,vi} from "vitest";
import App from "../App";
import {apiClient} from "../services/apiClient";

const authUser={id:"user-1",email:"ana@example.test",display_name:"Ana",authentication_mode:"session" as const};
const context={user:{id:"user-1",display_name:"Ana",email:"ana@example.test"},athletes:[],selected_athlete_id:null,selection_required:false};
function path(value="/"){window.history.replaceState({},"",value)}
beforeEach(()=>{vi.restoreAllMocks();localStorage.clear();apiClient.setActiveAthlete(null);path()});

describe("browser authentication flow",()=>{
 it("shows only the session bootstrap state while auth is unresolved",async()=>{let release!:(value:any)=>void;vi.spyOn(apiClient,"authMe").mockReturnValue(new Promise(resolve=>{release=resolve}));render(<App/>);expect(screen.getByRole("status")).toHaveTextContent("Comprobando sesión");expect(screen.queryByText("Navegación principal")).not.toBeInTheDocument();await act(async()=>release(authUser))});
 it("shows the accessible login form after a 401-equivalent failure",async()=>{vi.spyOn(apiClient,"authMe").mockRejectedValue(new Error("401"));render(<App/>);expect(await screen.findByRole("heading",{name:"Iniciar sesión"})).toBeVisible();expect(screen.getByLabelText("Correo electrónico")).toHaveAttribute("type","email");expect(screen.getByLabelText("Correo electrónico")).toHaveAttribute("autocomplete","email");expect(screen.getByLabelText("Contraseña")).toHaveAttribute("autocomplete","current-password");await waitFor(()=>expect(location.pathname).toBe("/login"))});
 it("reports generic invalid credentials and never exposes backend detail",async()=>{vi.spyOn(apiClient,"authMe").mockRejectedValue(new Error("401"));vi.spyOn(apiClient,"login").mockRejectedValue(new Error("internal database detail"));render(<App/>);const user=userEvent.setup();await user.type(await screen.findByLabelText("Correo electrónico"),"ana@example.test");await user.type(screen.getByLabelText("Contraseña"),"wrong password");await user.click(screen.getByRole("button",{name:"Iniciar sesión"}));expect(await screen.findByRole("alert")).toHaveTextContent("no son correctos");expect(screen.queryByText(/database/i)).not.toBeInTheDocument()});
 it("logs in, navigates to the app and preserves the multi-athlete selector",async()=>{vi.spyOn(apiClient,"authMe").mockRejectedValue(new Error("401"));vi.spyOn(apiClient,"login").mockResolvedValue(authUser);vi.spyOn(apiClient,"sessionContext").mockResolvedValue({...context,athletes:[{athlete_id:"athlete-a",label:"Atleta A",role:"owner",is_default:false,capabilities:["read_athlete_data"]},{athlete_id:"athlete-b",label:"Atleta B",role:"viewer",is_default:false,capabilities:["read_athlete_data"]}],selection_required:true});render(<App/>);const user=userEvent.setup();await user.type(await screen.findByLabelText("Correo electrónico"),"ana@example.test");await user.type(screen.getByLabelText("Contraseña"),"a secure password");await user.click(screen.getByRole("button",{name:"Iniciar sesión"}));expect(apiClient.login).toHaveBeenCalledWith({email:"ana@example.test",password:"a secure password"});expect(await screen.findByRole("heading",{name:"Selección de atleta necesaria"})).toBeVisible();expect(screen.getAllByRole("combobox",{name:/atleta/i})).toHaveLength(2)});
 it("restores an existing session and logs out only in session mode",async()=>{path("/settings");vi.spyOn(apiClient,"authMe").mockResolvedValue(authUser);vi.spyOn(apiClient,"sessionContext").mockResolvedValue(context);vi.spyOn(apiClient,"logout").mockResolvedValue(undefined);render(<App/>);const user=userEvent.setup();await user.click(await screen.findByRole("button",{name:/Ana/}));await user.click(screen.getByRole("menuitem",{name:"Cerrar sesión"}));expect(apiClient.logout).toHaveBeenCalledOnce();expect(await screen.findByRole("heading",{name:"Iniciar sesión"})).toBeVisible();expect(location.pathname).toBe("/login")});
 it("keeps development mode direct and does not offer an active logout",async()=>{path("/settings");vi.spyOn(apiClient,"authMe").mockResolvedValue({...authUser,authentication_mode:"development"});vi.spyOn(apiClient,"sessionContext").mockResolvedValue(context);render(<App/>);const user=userEvent.setup();await user.click(await screen.findByRole("button",{name:/Ana/}));expect(screen.getByRole("menuitem",{name:/Cerrar sesión/})).toBeDisabled()});
});