import {StrictMode} from "react";
import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {describe,expect,it,vi} from "vitest";
import type {ApiClient} from "../services/apiClient";
import {NewAthleteDialog} from "./NewAthleteDialog";
const created={id:"b",display_name:"Atleta B",timezone:"Europe/Madrid",unit_system:"metric" as const,role:"owner",is_default:false,capabilities:[]};
function setup(overrides:{create?:ReturnType<typeof vi.fn>;refresh?:ReturnType<typeof vi.fn>}={}){const create=overrides.create??vi.fn().mockResolvedValue(created),refresh=overrides.refresh??vi.fn().mockResolvedValue(true),close=vi.fn(),activated=vi.fn(),refreshUser=vi.fn();render(<StrictMode><NewAthleteDialog client={{createAthlete:create} as unknown as ApiClient} refreshContext={refresh} refreshUser={refreshUser} onClose={close} onActivated={activated}/></StrictMode>);return{create,refresh,close,activated,refreshUser}}
async function validForm(){await userEvent.type(screen.getByLabelText("Nombre del atleta"),"Atleta B");fireEvent.change(screen.getByLabelText("Zona horaria"),{target:{value:"Europe/Madrid"}})}
describe("NewAthleteDialog",()=>{
 it("validates required fields and closes with Cancelar",async()=>{const {create,close}=setup();fireEvent.change(screen.getByLabelText("Nombre del atleta"),{target:{value:"   "}});await userEvent.click(screen.getByRole("button",{name:"Crear atleta"}));expect(screen.getByRole("alert")).toHaveTextContent("obligatorio");expect(create).not.toHaveBeenCalled();await userEvent.click(screen.getByRole("button",{name:"Cancelar"}));expect(close).toHaveBeenCalledOnce()});
 it("creates once, refreshes with B, and activates under StrictMode",async()=>{let release!:(value:typeof created)=>void;const create=vi.fn().mockReturnValue(new Promise(resolve=>{release=resolve}));const {refresh,close,activated}=setup({create});await validForm();const form=screen.getByRole("dialog").querySelector("form")!;fireEvent.submit(form);fireEvent.submit(form);expect(create).toHaveBeenCalledOnce();expect(create).toHaveBeenCalledWith({display_name:"Atleta B",timezone:"Europe/Madrid",unit_system:"metric"});expect(screen.getByRole("button",{name:"Creando…"})).toBeDisabled();release(created);await waitFor(()=>expect(refresh).toHaveBeenCalledWith({preferredAthleteId:"b"}));await waitFor(()=>expect(activated).toHaveBeenCalledOnce());expect(close).toHaveBeenCalledOnce()});
 it("keeps input on network and 422 errors",async()=>{const create=vi.fn().mockRejectedValue(new Error("network failed"));setup({create});await validForm();await userEvent.click(screen.getByRole("button",{name:"Crear atleta"}));expect(await screen.findByRole("alert")).toHaveTextContent("conexión");expect(screen.getByLabelText("Nombre del atleta")).toHaveValue("Atleta B");create.mockRejectedValueOnce(new Error("TriCoach API request failed (422)"));await userEvent.click(screen.getByRole("button",{name:"Crear atleta"}));expect(await screen.findByRole("alert")).toHaveTextContent("zona horaria")});
 it("does not post again when refresh misses B and recovers by refresh only",async()=>{const refresh=vi.fn().mockResolvedValueOnce(false).mockResolvedValueOnce(true);const {create,activated}=setup({refresh});await validForm();await userEvent.click(screen.getByRole("button",{name:"Crear atleta"}));expect(await screen.findByRole("button",{name:"Actualizar atletas"})).toBeInTheDocument();expect(screen.getByRole("alert")).toHaveTextContent("se ha creado");await userEvent.click(screen.getByRole("button",{name:"Actualizar atletas"}));await waitFor(()=>expect(activated).toHaveBeenCalledOnce());expect(create).toHaveBeenCalledOnce();expect(refresh).toHaveBeenCalledTimes(2)});
 it("maps 409 and 403, and refreshes authentication after 401",async()=>{const create=vi.fn().mockRejectedValueOnce(new Error("request (409)")).mockRejectedValueOnce(new Error("request (403)")).mockRejectedValueOnce(new Error("request (401)"));const {refreshUser}=setup({create});await validForm();await userEvent.click(screen.getByRole("button",{name:"Crear atleta"}));expect(await screen.findByRole("alert")).toHaveTextContent("configuración actual");await userEvent.click(screen.getByRole("button",{name:"Crear atleta"}));expect(await screen.findByRole("alert")).toHaveTextContent("Actualiza la página");await userEvent.click(screen.getByRole("button",{name:"Crear atleta"}));await waitFor(()=>expect(refreshUser).toHaveBeenCalledOnce())});
});
