import {useEffect,useRef,useState,type FormEvent} from "react";
import type {ApiClient} from "../services/apiClient";
import type {AthleteCreateRequest,AthleteUnitSystem} from "../types/athlete";

type Props={client:ApiClient;refreshContext(options?:{preferredAthleteId?:string}):Promise<boolean>;refreshUser():Promise<void>;onClose():void;onActivated():void};
type Phase="idle"|"submitting"|"activating"|"recovery";
const initialTimezone=()=>{try{return Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC"}catch{return "UTC"}};
function apiMessage(error:unknown){const message=error instanceof Error?error.message:"";if(message.includes("(409)"))return "No se puede crear el atleta porque la configuración actual de atletas necesita revisión.";if(message.includes("(422)"))return "Revisa el nombre, la zona horaria y el sistema de unidades.";if(message.includes("(403)"))return "No se ha podido completar la operación. Actualiza la página e inténtalo de nuevo.";if(message.includes("(401)"))return "Tu sesión ha caducado. Vuelve a iniciar sesión.";return "No se ha podido crear el atleta. Comprueba tu conexión e inténtalo de nuevo."}
export function NewAthleteDialog({client,refreshContext,refreshUser,onClose,onActivated}:Props){
 const [name,setName]=useState(""),[timezone,setTimezone]=useState(initialTimezone),[unit,setUnit]=useState<AthleteUnitSystem>("metric"),[phase,setPhase]=useState<Phase>("idle"),[error,setError]=useState("");
 const first=useRef<HTMLInputElement>(null),submitting=useRef(false),createdId=useRef<string|null>(null);
 const busy=phase==="submitting"||phase==="activating";
 useEffect(()=>{first.current?.focus();const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!submitting.current)onClose()};document.addEventListener("keydown",escape);return()=>document.removeEventListener("keydown",escape)},[onClose]);
 async function activate(){if(!createdId.current)return;setPhase("activating");setError("");const activated=await refreshContext({preferredAthleteId:createdId.current});if(activated){onClose();onActivated();return}setPhase("recovery");setError("El atleta se ha creado, pero no se ha podido activar. Actualiza los atletas e inténtalo de nuevo.")}
 async function submit(event:FormEvent){event.preventDefault();if(submitting.current||createdId.current)return;const displayName=name.trim();if(!displayName){setError("El nombre del atleta es obligatorio.");return}if(name.length>200){setError("El nombre del atleta no puede superar 200 caracteres.");return}if(!timezone.trim()){setError("La zona horaria es obligatoria.");return}if(!unit){setError("Selecciona un sistema de unidades.");return}if(!client.createAthlete){setError("La creación de atletas no está disponible.");return}
  submitting.current=true;setPhase("submitting");setError("");const input:AthleteCreateRequest={display_name:name,timezone:timezone.trim(),unit_system:unit};try{const created=await client.createAthlete(input);createdId.current=created.id;setName(created.display_name);await activate()}catch(cause){setPhase("idle");setError(apiMessage(cause));if(cause instanceof Error&&cause.message.includes("(401)")){try{await refreshUser()}catch{/* AuthContext redirects when the session expired. */}}}finally{submitting.current=false}
 }
 return <div className="modal-backdrop" role="presentation"><section className="athlete-create-dialog" role="dialog" aria-modal="true" aria-labelledby="new-athlete-title"><form onSubmit={event=>void submit(event)}><header><div><h2 id="new-athlete-title">Nuevo atleta</h2><p>Crea un perfil deportivo independiente para esta cuenta.</p></div><button type="button" className="icon-button" aria-label="Cerrar formulario" disabled={busy} onClick={onClose}>×</button></header><label htmlFor="athlete-name">Nombre del atleta</label><input ref={first} id="athlete-name" maxLength={200} value={name} onChange={event=>setName(event.target.value)} disabled={busy}/><label htmlFor="athlete-timezone">Zona horaria</label><input id="athlete-timezone" value={timezone} onChange={event=>setTimezone(event.target.value)} disabled={busy} placeholder="Europe/Madrid"/><label htmlFor="athlete-units">Sistema de unidades</label><select id="athlete-units" value={unit} onChange={event=>setUnit(event.target.value as AthleteUnitSystem)} disabled={busy}><option value="metric">Métrico</option><option value="imperial">Imperial</option></select>{error&&<p className="form-error" role="alert">{error}</p>}<div className="sr-only" role="status" aria-live="polite">{phase==="submitting"?"Creando atleta…":phase==="activating"?"Activando atleta…":""}</div><footer>{phase==="recovery"?<button type="button" className="button button--primary" onClick={()=>void activate()}>Actualizar atletas</button>:<><button type="button" className="button" disabled={busy} onClick={onClose}>Cancelar</button><button type="submit" className="button button--primary" disabled={busy}>{phase==="submitting"?"Creando…":phase==="activating"?"Activando…":"Crear atleta"}</button></>}</footer></form></section></div>
}
