import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {describe,expect,it,vi} from "vitest";
import type {ApiClient} from "../services/apiClient";
import {ActivitySyncButton,activitySyncCompletedEvent} from "./ActivitySyncButton";

const status=(state:string,error_category:string|null=null,stage="completed")=>({job_id:"j1",provider:"strava" as const,status:state as never,imported_count:1,updated_count:0,skipped_count:0,failed_count:0,page:1,last_external_activity_id:null,started_at:null,updated_at:"2026-07-16T08:00:00Z",completed_at:null,next_resume_at:null,error_category,stage:stage as never,processed_count:stage==="completed"?1:0,affected_start_date:"2026-07-16",affected_end_date:"2026-07-16"});
function client(overrides:Partial<ApiClient>={}):ApiClient{return {stravaStatus:vi.fn().mockResolvedValue({last_sync_at:"2026-07-15T08:00:00Z"}),latestImport:vi.fn().mockResolvedValue(status("not_started",null,"not_started")),startImport:vi.fn().mockResolvedValue({job_id:"j1",status:"queued"}),importStatus:vi.fn().mockResolvedValue(status("succeeded")),...overrides} as ApiClient}

describe("ActivitySyncButton",()=>{
 it("prevents duplicate starts, announces derived completion and refreshes",async()=>{let release:(value:ReturnType<typeof status>)=>void=()=>{};const c=client({importStatus:vi.fn(()=>new Promise<ReturnType<typeof status>>(resolve=>{release=resolve}))}),listener=vi.fn();window.addEventListener(activitySyncCompletedEvent,listener);render(<ActivitySyncButton athleteId="jenny" client={c} pollDelayMs={0}/>);const button=await screen.findByRole("button",{name:"Sincronizar actividades"});await userEvent.dblClick(button);expect(button).toBeDisabled();expect(c.startImport).toHaveBeenCalledTimes(1);release(status("succeeded"));expect(await screen.findByText(/Actividades y estadísticas actualizadas/)).toBeInTheDocument();await waitFor(()=>expect(listener).toHaveBeenCalledTimes(1));expect(listener.mock.calls[0][0].detail.athleteId).toBe("jenny");window.removeEventListener(activitySyncCompletedEvent,listener)});
 it("shows processing progress from backend state",async()=>{render(<ActivitySyncButton client={client({importStatus:vi.fn().mockResolvedValueOnce(status("running",null,"processing"))})} pollDelayMs={10000}/>);await userEvent.click(await screen.findByRole("button",{name:"Sincronizar actividades"}));expect(await screen.findByText("Preparando tus datos de Strava…")).toBeInTheDocument();expect(screen.getByRole("button")).toHaveTextContent("Procesando datos")});
 it("offers retry after recoverable processing failure",async()=>{const c=client({importStatus:vi.fn().mockResolvedValue(status("partially_succeeded","post_processing_failed","processing"))});render(<ActivitySyncButton client={c}/>);await userEvent.click(await screen.findByRole("button",{name:"Sincronizar actividades"}));expect(await screen.findByRole("alert")).toHaveTextContent("Se importaron tus actividades");expect(screen.getByRole("button")).toHaveTextContent("Reintentar procesamiento");await userEvent.click(screen.getByRole("button"));expect(c.startImport).toHaveBeenCalledTimes(2)});
 it("announces failure and rate limit",async()=>{const {unmount}=render(<ActivitySyncButton client={client({importStatus:vi.fn().mockResolvedValue(status("failed","provider_error","importing"))})}/>);await userEvent.click(await screen.findByRole("button",{name:"Sincronizar actividades"}));expect(await screen.findByText("Error al sincronizar.")).toBeInTheDocument();unmount();render(<ActivitySyncButton client={client({importStatus:vi.fn().mockResolvedValue(status("retry_scheduled","rate_limited","importing"))})}/>);await userEvent.click(await screen.findByRole("button",{name:"Sincronizar actividades"}));expect(await screen.findByText(/Límite de Strava alcanzado/)).toBeInTheDocument()});
 it("ignores a stale response after the Athlete changes",async()=>{let release!:(value:ReturnType<typeof status>)=>void;const c=client({latestImport:vi.fn().mockImplementationOnce(()=>new Promise(resolve=>{release=resolve})).mockResolvedValueOnce(status("not_started",null,"not_started"))});const view=render(<ActivitySyncButton athleteId="carlos" client={c}/>);view.rerender(<ActivitySyncButton athleteId="jenny" client={c}/>);release(status("partially_succeeded","post_processing_failed","processing"));await waitFor(()=>expect(c.latestImport).toHaveBeenCalledTimes(2));expect(screen.queryByRole("alert")).not.toBeInTheDocument()});
});