import {beforeEach,describe,expect,it,vi} from "vitest";import {ATHLETE_HEADER} from "../types/sessionContext";import {CSRF_HEADER_NAME,FetchApiClient} from "./apiClient";
const json=(value:unknown)=>Promise.resolve(new Response(JSON.stringify(value),{status:200,headers:{"Content-Type":"application/json"}}));beforeEach(()=>vi.restoreAllMocks());
describe("FetchApiClient athlete isolation",()=>{
 it("keeps context and health public and injects one current athlete header in sports requests",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json({}));const client=new FetchApiClient("http://api");await client.sessionContext();await client.health();client.setActiveAthlete("athlete-a");await client.activities();const calls=fetchMock.mock.calls;expect(new Headers(calls[0][1]?.headers).has(ATHLETE_HEADER)).toBe(false);expect(new Headers(calls[1][1]?.headers).has(ATHLETE_HEADER)).toBe(false);expect(new Headers(calls[2][1]?.headers).get(ATHLETE_HEADER)).toBe("athlete-a")});
 it("adds the active athlete to every sports area through the single transport",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json([]));const client=new FetchApiClient("http://api");client.setActiveAthlete("athlete-z");await Promise.all([client.activities(),client.dashboardSummary(),client.listManualStrengthSessions(),client.performanceProfile(),client.performanceReferences(),client.performanceZones(),client.getDailyTrainingLoad({startDate:"2026-01-01",endDate:"2026-01-02",timezoneName:"UTC"}),client.listTrainingStatus({startDate:"2026-01-01",endDate:"2026-01-02",timezoneName:"UTC"}),client.stravaStatus(),client.startStravaConnection(),client.latestImport()]);for(const [,init] of fetchMock.mock.calls)expect(new Headers(init?.headers).get(ATHLETE_HEADER)).toBe("athlete-z")});
 it("uses the new athlete for every request after a switch",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json({items:[],total:0,limit:10,offset:0}));const client=new FetchApiClient("http://api");client.setActiveAthlete("a");await client.activities();client.setActiveAthlete("b");await client.activities();expect(new Headers(fetchMock.mock.calls[1][1]?.headers).get(ATHLETE_HEADER)).toBe("b")});
 it("rejects a late response from athlete A after B becomes active",async()=>{let releaseA!:(value:Response)=>void;const slow=new Promise<Response>(resolve=>{releaseA=resolve});const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementationOnce(()=>slow).mockImplementationOnce(()=>json({total:2,limit:10,offset:0,items:[]}));const client=new FetchApiClient("http://api");client.setActiveAthlete("a");const requestA=client.activities();client.setActiveAthlete("b");const resultB=await client.activities();releaseA(new Response(JSON.stringify({total:99,items:[]}),{status:200}));await expect(requestA).rejects.toMatchObject({name:"AbortError"});expect(resultB.total).toBe(2);expect(fetchMock).toHaveBeenCalledTimes(2)});
 it("reports authorization errors once without retrying",async()=>{const handler=vi.fn(),fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({detail:{code:"athlete_permission_denied"}}),{status:403}));const client=new FetchApiClient("http://api");client.setActiveAthlete("a");client.setAuthorizationErrorHandler(handler);await expect(client.activities()).rejects.toThrow("athlete_permission_denied");expect(handler).toHaveBeenCalledOnce();expect(fetchMock).toHaveBeenCalledOnce()}); it("includes credentials in authentication calls",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json({id:"u",email:"u@example.test",display_name:"U",authentication_mode:"session"}));const client=new FetchApiClient("http://api");await client.authMe();await client.login({email:"u@example.test",password:"password"});for(const [,init] of fetchMock.mock.calls)expect(init?.credentials).toBe("include")});
 it("reads the CSRF cookie for mutations but not login or GET",async()=>{Object.defineProperty(document,"cookie",{configurable:true,value:"tricoach_csrf=csrf-value"});const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json({}));const client=new FetchApiClient("http://api");await client.login({email:"u@example.test",password:"password"});await client.authMe();await client.logout();expect(new Headers(fetchMock.mock.calls[0][1]?.headers).has(CSRF_HEADER_NAME)).toBe(false);expect(new Headers(fetchMock.mock.calls[1][1]?.headers).has(CSRF_HEADER_NAME)).toBe(false);expect(new Headers(fetchMock.mock.calls[2][1]?.headers).get(CSRF_HEADER_NAME)).toBe("csrf-value")});
 it("uses central credentials and CSRF for account calls without athlete scope",async()=>{Object.defineProperty(document,"cookie",{configurable:true,value:"tricoach_csrf=account-csrf"});const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json({}));const client=new FetchApiClient("http://api");await client.getAccount();await client.updateAccount({display_name:null});await client.changePassword({current_password:"current",new_password:"new password"});expect(fetchMock.mock.calls.map(call=>new URL(call[0] as string).pathname)).toEqual(["/account","/account","/account/password"]);for(const [,init] of fetchMock.mock.calls){expect(init?.credentials).toBe("include");expect(new Headers(init?.headers).has(ATHLETE_HEADER)).toBe(false)}expect(new Headers(fetchMock.mock.calls[0][1]?.headers).has(CSRF_HEADER_NAME)).toBe(false);expect(new Headers(fetchMock.mock.calls[1][1]?.headers).get(CSRF_HEADER_NAME)).toBe("account-csrf");expect(JSON.parse(fetchMock.mock.calls[2][1]?.body as string)).toEqual({current_password:"current",new_password:"new password"})});
});
describe("FetchApiClient athlete creation",()=>{it("posts the exact account-scoped payload with central credentials and CSRF",async()=>{Object.defineProperty(document,"cookie",{configurable:true,value:"tricoach_csrf=create-csrf"});const response={id:"b",display_name:"Atleta B",timezone:"Europe/Madrid",unit_system:"metric" as const,role:"owner",is_default:false,capabilities:["read_athlete_data"]};const fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify(response),{status:201,headers:{"Content-Type":"application/json"}}));const client=new FetchApiClient("http://api");client.setActiveAthlete("a");await expect(client.createAthlete({display_name:" Atleta B ",timezone:"Europe/Madrid",unit_system:"metric"})).resolves.toEqual(response);const [url,init]=fetchMock.mock.calls[0];expect(url).toBe("http://api/athletes");expect(init?.method).toBe("POST");expect(init?.credentials).toBe("include");expect(new Headers(init?.headers).get(CSRF_HEADER_NAME)).toBe("create-csrf");expect(new Headers(init?.headers).has(ATHLETE_HEADER)).toBe(false);expect(JSON.parse(init?.body as string)).toEqual({display_name:" Atleta B ",timezone:"Europe/Madrid",unit_system:"metric"})})});
describe("FetchApiClient athlete profile",()=>{it("uses athlete scope for GET and central CSRF for an exact PATCH",async()=>{Object.defineProperty(document,"cookie",{configurable:true,value:"tricoach_csrf=profile-csrf"});const response={id:"a",display_name:"Jenny",timezone:"Europe/Madrid",unit_system:"metric",birth_year:null,sex_for_training_context:null,height_m:1.78,weight_kg:72.4,updated_at:"2026-08-12T10:00:00Z",completeness:{status:"minimal",missing_recommended_fields:["birth_year"]}};const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json(response));const client=new FetchApiClient("http://api");client.setActiveAthlete("a");await expect(client.getAthleteProfile()).resolves.toEqual(response);await client.updateAthleteProfile({weight_kg:72.4});expect(fetchMock.mock.calls.map(call=>new URL(call[0] as string).pathname)).toEqual(["/athlete/profile","/athlete/profile"]);for(const [,init] of fetchMock.mock.calls)expect(new Headers(init?.headers).get(ATHLETE_HEADER)).toBe("a");expect(fetchMock.mock.calls[1][1]?.method).toBe("PATCH");expect(fetchMock.mock.calls[1][1]?.credentials).toBe("include");expect(new Headers(fetchMock.mock.calls[1][1]?.headers).get(CSRF_HEADER_NAME)).toBe("profile-csrf");expect(JSON.parse(fetchMock.mock.calls[1][1]?.body as string)).toEqual({weight_kg:72.4})})});

describe("FetchApiClient coach assignment revocation",()=>{
 it("sends the real membership id in the exact DELETE URL",async()=>{Object.defineProperty(document,"cookie",{configurable:true,value:"tricoach_csrf=revoke-csrf"});const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json({membership_id:"membership-123"}));const client=new FetchApiClient("http://api");await client.revokeCoachAssignment("membership-123");const [url,init]=fetchMock.mock.calls[0];expect(url).toBe("http://api/coach-assignments/membership-123");expect(init?.method).toBe("DELETE");expect(new Headers(init?.headers).get(CSRF_HEADER_NAME)).toBe("revoke-csrf")});
 it("rejects an empty or undefined membership id without issuing fetch",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch");const client=new FetchApiClient("http://api");await expect(client.revokeCoachAssignment("")).rejects.toThrow("invalid_membership_id");await expect((client.revokeCoachAssignment as any)(undefined)).rejects.toThrow("invalid_membership_id");expect(fetchMock).not.toHaveBeenCalled()});
});
