import {beforeEach,describe,expect,it,vi} from "vitest";import {ATHLETE_HEADER} from "../types/sessionContext";import {FetchApiClient} from "./apiClient";
const json=(value:unknown)=>Promise.resolve(new Response(JSON.stringify(value),{status:200,headers:{"Content-Type":"application/json"}}));beforeEach(()=>vi.restoreAllMocks());
describe("FetchApiClient athlete isolation",()=>{
 it("keeps context and health public and injects one current athlete header in sports requests",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json({}));const client=new FetchApiClient("http://api");await client.sessionContext();await client.health();client.setActiveAthlete("athlete-a");await client.activities();const calls=fetchMock.mock.calls;expect(new Headers(calls[0][1]?.headers).has(ATHLETE_HEADER)).toBe(false);expect(new Headers(calls[1][1]?.headers).has(ATHLETE_HEADER)).toBe(false);expect(new Headers(calls[2][1]?.headers).get(ATHLETE_HEADER)).toBe("athlete-a")});
 it("adds the active athlete to every sports area through the single transport",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json([]));const client=new FetchApiClient("http://api");client.setActiveAthlete("athlete-z");await Promise.all([client.activities(),client.dashboardSummary(),client.listManualStrengthSessions(),client.performanceProfile(),client.performanceReferences(),client.performanceZones(),client.getDailyTrainingLoad({startDate:"2026-01-01",endDate:"2026-01-02",timezoneName:"UTC"}),client.listTrainingStatus({startDate:"2026-01-01",endDate:"2026-01-02",timezoneName:"UTC"}),client.stravaStatus(),client.startStravaConnection(),client.latestImport()]);for(const [,init] of fetchMock.mock.calls)expect(new Headers(init?.headers).get(ATHLETE_HEADER)).toBe("athlete-z")});
 it("uses the new athlete for every request after a switch",async()=>{const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementation(()=>json({items:[],total:0,limit:10,offset:0}));const client=new FetchApiClient("http://api");client.setActiveAthlete("a");await client.activities();client.setActiveAthlete("b");await client.activities();expect(new Headers(fetchMock.mock.calls[1][1]?.headers).get(ATHLETE_HEADER)).toBe("b")});
 it("rejects a late response from athlete A after B becomes active",async()=>{let releaseA!:(value:Response)=>void;const slow=new Promise<Response>(resolve=>{releaseA=resolve});const fetchMock=vi.spyOn(globalThis,"fetch").mockImplementationOnce(()=>slow).mockImplementationOnce(()=>json({total:2,limit:10,offset:0,items:[]}));const client=new FetchApiClient("http://api");client.setActiveAthlete("a");const requestA=client.activities();client.setActiveAthlete("b");const resultB=await client.activities();releaseA(new Response(JSON.stringify({total:99,items:[]}),{status:200}));await expect(requestA).rejects.toMatchObject({name:"AbortError"});expect(resultB.total).toBe(2);expect(fetchMock).toHaveBeenCalledTimes(2)});
 it("reports authorization errors once without retrying",async()=>{const handler=vi.fn(),fetchMock=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({detail:{code:"athlete_permission_denied"}}),{status:403}));const client=new FetchApiClient("http://api");client.setActiveAthlete("a");client.setAuthorizationErrorHandler(handler);await expect(client.activities()).rejects.toThrow("athlete_permission_denied");expect(handler).toHaveBeenCalledOnce();expect(fetchMock).toHaveBeenCalledOnce()});
});
