export interface HealthResponse { status:string; service:string; }
export interface StravaStatus { provider:"strava"; connection_status:string; connected:boolean; external_athlete_id:string|null; granted_scopes:string[]; connected_at:string|null; updated_at:string|null; token_expires_at:string|null; requires_reconnect:boolean; last_sync_at:string|null; message:string; }
export interface ActivitySummary { id:string; external_activity_id:string|null; name:string; sport_type:string; start_time:string; athlete_timezone:string; distance_metres:number|null; moving_time_seconds:number|null; elapsed_time_seconds:number; elevation_metres:number|null; average_heart_rate:number|null; average_watts:number|null; trainer:boolean|null; manual:boolean|null; visibility:string|null; }
export interface ActivityPage { total:number; limit:number; offset:number; items:ActivitySummary[]; }
export type SyncStatus="not_started"|"queued"|"running"|"retry_scheduled"|"succeeded"|"partially_succeeded"|"failed"|"cancelled";
export interface ImportStatus { job_id:string|null; provider:"strava"; status:SyncStatus; imported_count:number; updated_count:number; skipped_count:number; failed_count:number; page:number; last_external_activity_id:string|null; started_at:string|null; updated_at:string; completed_at:string|null; next_resume_at:string|null; error_category:string|null; }
export interface ImportStart { job_id:string; status:SyncStatus; }
export interface SportBreakdown { sport_type:string; activity_count:number; moving_time_seconds:number; distance_metres:number; elevation_metres:number; }
export interface DashboardSummary { period:string; period_start:string; period_end:string; activity_count:number; total_moving_time_seconds:number; total_distance_metres:number; total_elevation_metres:number; active_days:number; longest_activity_seconds:number; longest_activity_distance_metres:number; sport_breakdown:SportBreakdown[]; }
export interface WeeklyTrend { week_start:string; week_end:string; activity_count:number; moving_time_seconds:number; distance_metres:number; elevation_metres:number; active_days:number; }
export interface Consistency { weeks:number; active_weeks:number; current_training_streak_weeks:number; longest_training_streak_weeks:number; average_active_days_per_week:number; average_moving_time_seconds_per_week:number; last_activity_at:string|null; }
export interface ActivityDetail extends ActivitySummary { max_heart_rate:number|null; average_speed_metres_per_second:number|null; max_speed_metres_per_second:number|null; average_cadence:number|null; weighted_average_watts:number|null; commute:boolean|null; created_at:string; updated_at:string; provider_description?:string|null; calories?:number|null; device_name?:string|null; gear_id?:string|null; suffer_score?:number|null; perceived_exertion?:number|null; total_work_joules?:number|null; kilojoules?:number|null; average_temperature_celsius?:number|null; max_watts?:number|null; workout_type?:number|null; achievement_count?:number|null; kudos_count?:number|null; athlete_count?:number|null; photo_count?:number|null; has_heartrate?:boolean|null; has_power_meter?:boolean|null; hide_from_home?:boolean|null; private?:boolean|null; flagged?:boolean|null; enriched_at?:string|null; enrichment_status?:string|null; enrichment_error_category?:string|null; }
export interface EnrichmentStart { job_id:string; status:SyncStatus; }
export interface EnrichmentStatus { job_id:string; status:SyncStatus; selected_count:number; enriched_count:number; updated_count:number; skipped_count:number; failed_count:number; last_activity_id:string|null; started_at:string|null; updated_at:string; completed_at:string|null; next_resume_at:string|null; error_category:string|null; }
export interface ActivityFilterOptions { sport_types:string[]; visibility_values:string[]; minimum_activity_date:string|null; maximum_activity_date:string|null; }


export interface EvidenceLap { lap_index:number;name:string|null;start_date:string|null;elapsed_time_seconds:number|null;moving_time_seconds:number|null;distance_metres:number|null;elevation_metres:number|null;average_speed_metres_per_second:number|null;maximum_speed_metres_per_second:number|null;average_heart_rate:number|null;maximum_heart_rate:number|null;average_cadence:number|null;average_watts:number|null; }
export interface EvidenceStream { stream_type:string;values:(number|null)[];sample_count:number;original_sample_count:number;downsampled:boolean;series_type:string|null; }
export interface ActivityEvidence { activity_id:string;sport_type:string;laps:EvidenceLap[];streams:Record<string,EvidenceStream>;route:{available:boolean;retention_enabled:boolean;sample_count:number;polyline:string|null};fetched_at:string|null;partial:boolean;missing_streams:string[];location_status:"available"|"unavailable"|"privacy_disabled"; }
export interface EvidenceStart { job_id:string;status:SyncStatus; }
export interface EvidenceJob { job_id:string;status:SyncStatus;selected_count:number;laps_imported:number;streams_imported:number;activities_completed:number;skipped_count:number;failed_count:number;last_activity_id:string|null;started_at:string|null;updated_at:string;completed_at:string|null;next_resume_at:string|null;error_category:string|null;location_retention_enabled:boolean; }