export type CompetitionPriority = "A" | "B" | "C";
export type CompetitionCategory = "triathlon" | "duathlon" | "aquathlon" | "running" | "cycling" | "swimming";
export type CompetitionSegmentSport = "swim" | "bike" | "run";
export interface CompetitionGoalSegment {id?: string;position: number;sport: CompetitionSegmentSport;distance_m: number;label: string | null;elevation_gain_m: number | null}
export interface CompetitionGoal {id:string;athlete_profile_id:string;name:string;event_date:string;event_start_time:string|null;timezone:string;event_category:CompetitionCategory;event_format:string;priority:CompetitionPriority;segments:CompetitionGoalSegment[];distance_m:number|null;swim_distance_m:number|null;bike_distance_m:number|null;run_distance_m:number|null;target_finish_time_seconds:number|null;notes:string|null;city:string|null;region:string|null;country:string|null;source_provider:string|null;source_external_id:string|null;source_url:string|null;source_retrieved_at:string|null;status:"active"|"completed"|"cancelled";created_by_user_id:string;created_at:string;updated_at:string}
export interface CompetitionGoalCreate {name:string;event_date:string;event_category:CompetitionCategory;event_format:string;priority:CompetitionPriority;segments:Omit<CompetitionGoalSegment,"id"|"position">[];target_finish_time_seconds?:number|null;notes?:string|null;city?:string|null;region?:string|null;country?:string|null;source_provider?:"tavily";source_url?:string}
export type CompetitionGoalUpdate=Partial<CompetitionGoalCreate>&{status?:CompetitionGoal["status"]};
export interface CatalogProvider {provider:string;label:string;configured:boolean;supported_categories:CompetitionCategory[];search_mode?:"structured"|"web";supports_structured_detail?:boolean;supports_structured_import?:boolean;supports_search_to_manual_goal?:boolean}
export interface WebCompetitionSearchResult {id:string;title:string;url:string;snippet:string;source_domain:string;source_label:string;source_kind:string;result_kind:"event_candidate"|"event_listing"|"other_sports_resource";hints:{possible_date:string|null;possible_location:string|null;possible_category:string|null;possible_distance:string|null}}
export interface WebCompetitionSearchResponse {results:WebCompetitionSearchResult[];has_more:boolean;phase:"initial"|"more"}
export interface CatalogEvent {provider:string;external_id:string;name:string;start_date:string;end_date:string|null;category:CompetitionCategory|null;event_format:string|null;city:string|null;region:string|null;country:string|null;latitude:number|null;longitude:number|null;source_url:string|null;segments:CompetitionGoalSegment[];confidence?:"high"|"medium"|"low"|null;evidence?:{url:string;title:string|null;official:boolean;source_kind?:"official"|"registration"|"timing"|"specialized_calendar"|"web"|null}[];retrieved_at:string}
export interface CatalogSearchFilters {text?:string;category?:CompetitionCategory|"";start_date?:string;end_date?:string;location?:string;provider?:string}

export interface AvailabilitySlot {weekday:number;available_minutes:number;max_sessions:number;earliest_time?:string|null;latest_time?:string|null}
export interface PlanningPreferences {availability_slots:AvailabilitySlot[];max_sessions_per_day:number;max_sessions_per_week:number;preferred_rest_days:number[];preferred_long_run_day:number|null;preferred_long_bike_day:number|null;strength_sessions_per_week:number}
export interface PlanningPreferencesVersion {id:string;athlete_profile_id:string;version_number:number;created_at:string;preferences:PlanningPreferences}
export interface PlanningPreviewRequest {planning_date:string;start_date:string;horizon_end_date?:string;goal_ids:string[];preferences:PlanningPreferences}
export interface PlanningWarning {code:string;severity:"WARNING"|"ERROR";blocking:boolean;context:Record<string,string|number|boolean|null>}
export interface PreviewPrescription {date:string;discipline:string;session_type:string;purpose:string;intensity:string;priority:string;key_session:boolean;optional:boolean;target_duration_minutes:number|null;target_load:number|null;phase:string;related_goal_ids:string[]}
export interface WorkoutTarget {metric:string;mode:string;reference?:string;minimum?:number;maximum?:number;reference_value?:number;reference_unit?:string;resolved_minimum?:number;resolved_maximum?:number;resolved_unit?:string}
export interface WorkoutNode {kind:"step"|"repeat";phase?:string;duration?:{mode:string;seconds?:number};target?:WorkoutTarget;instructions?:string;repetitions?:number;steps?:WorkoutNode[]}
export interface StructuredWorkoutDefinition {schema_version:number;sport:string;steps:WorkoutNode[]}
export interface PreviewWorkout {buildable:boolean;definition:StructuredWorkoutDefinition|null;warnings?:Array<{code:string;context?:Record<string,unknown>}>;decisions?:Array<{code:string;context?:Record<string,unknown>}>}
export interface PreviewWeek {week_start:string;week_end:string;sessions:PreviewPrescription[];rest_dates:string[];unavailable_dates:string[];budget_target_load:number|null;planned_load:number|null;warnings:PlanningWarning[]}
export interface PlanningPreviewArtifact {plan_start:string;plan_end:string;fingerprint:string;context_fingerprint:string;timezone_name:string;goals:Array<{competition_goal_id:string;event_date:string;priority:string;role?:string|null;category:string;event_format:string;city?:string|null;region?:string|null;country?:string|null}>;sessions:Array<{prescription:PreviewPrescription;workout:PreviewWorkout}>;session_plan:{weeks:PreviewWeek[];warnings:PlanningWarning[]};season_structure:Record<string,unknown>;weekly_budget_plan:Record<string,unknown>;algorithm_version:string;configuration_version:string}
export interface PlanningPreview {id:string;status:"pending"|"accepted"|string;created_at:string;accepted_at:string|null;accepted_training_plan_id:string|null;artifact:PlanningPreviewArtifact}
export interface TrainingPlanSession {id:string;scheduled_date:string;sport:string;title:string;description:string|null;planned_duration_seconds:number;workout:StructuredWorkoutDefinition|null}
export interface LinkedActivitySummary {id:string;name:string;sport:string;started_at:string;timezone:string;duration_seconds:number;distance_meters:number|null}
export interface PlannedSessionActivityLink {id:string;planned_training_session_id:string;completed_activity_id:string;match_source:"automatic"|"manual";match_confidence:"high"|"medium"|"low";created_at:string;activity:LinkedActivitySummary}
export interface ActivityLinkCandidate extends LinkedActivitySummary {local_date:string;confidence:"high"|"medium"|"low";evidence:string[]}
export interface AutoMatchResult {classification:"clear_match"|"ambiguous"|"no_match";reason:string;candidates:ActivityLinkCandidate[];link:PlannedSessionActivityLink|null}
export interface TrainingPlan {id:string;athlete_profile_id:string;title:string;start_date:string;end_date:string;status:string;origin:string;algorithm_version:string;goals:Array<{competition_goal_id:string;relationship:string}>;sessions:TrainingPlanSession[]}
export interface AcceptedTrainingPlan {training_plan_id:string;preview_id:string;status:string}
