export type CompetitionPriority = "A" | "B" | "C";
export type CompetitionCategory = "triathlon" | "duathlon" | "aquathlon" | "running" | "cycling" | "swimming";
export type CompetitionSegmentSport = "swim" | "bike" | "run";
export interface CompetitionGoalSegment {id?: string;position: number;sport: CompetitionSegmentSport;distance_m: number;label: string | null;elevation_gain_m: number | null}
export interface CompetitionGoal {id:string;athlete_profile_id:string;name:string;event_date:string;event_start_time:string|null;timezone:string;event_category:CompetitionCategory;event_format:string;priority:CompetitionPriority;segments:CompetitionGoalSegment[];distance_m:number|null;swim_distance_m:number|null;bike_distance_m:number|null;run_distance_m:number|null;target_finish_time_seconds:number|null;notes:string|null;city:string|null;region:string|null;country:string|null;source_provider:string|null;source_external_id:string|null;source_url:string|null;source_retrieved_at:string|null;status:"active"|"completed"|"cancelled";created_by_user_id:string;created_at:string;updated_at:string}
export interface CompetitionGoalCreate {name:string;event_date:string;event_category:CompetitionCategory;event_format:string;priority:CompetitionPriority;segments:Omit<CompetitionGoalSegment,"id"|"position">[];target_finish_time_seconds?:number|null;notes?:string|null;city?:string|null;region?:string|null;country?:string|null;source_provider?:"tavily";source_url?:string}
export type CompetitionGoalUpdate=Partial<CompetitionGoalCreate>&{status?:CompetitionGoal["status"]};
export interface CatalogProvider {provider:string;label:string;configured:boolean;supported_categories:CompetitionCategory[];search_mode?:"structured"|"web";supports_structured_detail?:boolean;supports_structured_import?:boolean;supports_search_to_manual_goal?:boolean}
export interface WebCompetitionSearchResult {id:string;title:string;url:string;snippet:string;source_domain:string;source_label:string;source_kind:string;result_kind:"event_candidate"|"event_listing"|"other_sports_resource";hints:{possible_date:string|null;possible_location:string|null;possible_category:string|null;possible_distance:string|null}}
export interface WebCompetitionSearchResponse {results:WebCompetitionSearchResult[];has_more:boolean;phase:"initial"|"more"}
export interface CatalogEvent {provider:string;external_id:string;name:string;start_date:string;end_date:string|null;category:CompetitionCategory|null;event_format:string|null;city:string|null;region:string|null;country:string|null;latitude:number|null;longitude:number|null;source_url:string|null;segments:CompetitionGoalSegment[];confidence?:"high"|"medium"|"low"|null;evidence?:{url:string;title:string|null;official:boolean;source_kind?:"official"|"registration"|"timing"|"specialized_calendar"|"web"|null}[];retrieved_at:string}
export interface CatalogSearchFilters {text?:string;category?:CompetitionCategory|"";start_date?:string;end_date?:string;location?:string;provider?:string}
