import { useEffect,useRef,useState } from "react";
import { AppLink } from "../../app/usePathname";
import { apiClient,type ApiClient } from "../../services/apiClient";
import type { ActivityDetail,EnrichmentStatus } from "../../types/api";
import {ActivityEvidenceSection} from "./ActivityEvidenceSection";
import {ActivityMetricsSection} from "./ActivityMetricsSection";
import { displaySport,formatActivityDateLine,formatCadence,formatCompactDuration,formatCommute,formatDistance,formatDuration,formatElevation,formatManual,formatPower,formatSportSpeed,formatTrainer,formatVisibility,softValue,sportIcon } from "../../utils/format";
interface Metric{label:string;value:string;icon?:string}
interface BadgeMetric{label:string;value:string;icon:string;tone:string}
function MetricValue({value}:{value:string}){if(value==="—")return <span className="metric-empty" aria-label="Sin datos">—</span>;if(!/^\d/.test(value))return <>{value}</>;const parts=value.split(/(\d+(?:[.,:]\d+)?)/g).filter(Boolean);return <>{parts.map((part,index)=>/^\d/.test(part)?<strong key={index}>{part}</strong>:<small key={index}>{part}</small>)}</>}
function MetricSection({title,items,primary=false}:{title:string;items:Metric[];primary?:boolean}){const id=`summary-${title.replaceAll(" ","-").toLowerCase()}`;return <section className={`summary-section ${primary?"summary-section--primary":""}`} aria-labelledby={id}><h2 id={id}>{title}</h2><dl className="summary-metrics">{items.map(item=><div className="summary-metric" key={item.label}>{item.icon&&<span className="performance-icon" aria-hidden="true">{item.icon}</span>}<dt>{item.label}</dt><dd><MetricValue value={item.value}/></dd></div>)}</dl></section>}
function MetadataSection({items}:{items:BadgeMetric[]}){return <section className="summary-section summary-section--metadata" aria-labelledby="summary-information"><h2 id="summary-information">Información de la actividad</h2><dl className="metadata-grid">{items.map(item=><div key={item.label}><dt>{item.label}</dt><dd><span className={`metadata-badge metadata-badge--${item.tone}`}><span aria-hidden="true">{item.icon}</span>{item.value}</span></dd></div>)}</dl></section>}
const heart=(value:number|null)=>value===null||!Number.isFinite(value)||value<=0?"—":`${Math.round(value)} ppm`;
const soft=(value:string)=>softValue(value);
const number=(value:number|null|undefined,unit:string)=>value===null||value===undefined||!Number.isFinite(value)?"—":`${new Intl.NumberFormat("es-ES",{maximumFractionDigits:1}).format(value)} ${unit}`;
const statusLabel=(status:string|null|undefined)=>({succeeded:"Actualizados",running:"Actualizando",queued:"En cola",retry_scheduled:"En pausa",failed:"Error",unavailable:"No disponible"}[status??""]??"Sin actualizar");
export function ActivitySummaryPage({activityId,client=apiClient}:{activityId:string;client?:ApiClient}){
 const [activity,setActivity]=useState<ActivityDetail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false),[job,setJob]=useState<EnrichmentStatus|null>(null),[message,setMessage]=useState<string|null>(null),mounted=useRef(true);
 const load=()=>client.activityDetail(activityId).then(value=>{if(mounted.current)setActivity(value)});
 useEffect(()=>{mounted.current=true;setLoading(true);setError(false);load().catch(()=>setError(true)).finally(()=>setLoading(false));return()=>{mounted.current=false}},[activityId,client]);
 const poll=async(jobId:string)=>{if(!client.enrichmentStatus)return;try{const next=await client.enrichmentStatus(jobId);if(!mounted.current)return;setJob(next);if(next.status==="succeeded"||next.status==="partially_succeeded"){await load();setMessage(next.status==="succeeded"?"Detalles actualizados correctamente.":"Detalles actualizados con algunas incidencias.");return}if(next.status==="failed"){setMessage("No se pudieron actualizar los detalles. Inténtalo de nuevo más tarde.");return}if(next.status==="retry_scheduled"){setMessage("Actualización en pausa. Puedes reanudarla de forma segura.");return}window.setTimeout(()=>void poll(jobId),500)}catch{if(mounted.current)setMessage("No se pudo consultar la actualización. Inténtalo de nuevo más tarde.")}};
 const start=async()=>{if(!client.startEnrichment)return;setMessage(null);setJob({job_id:"",status:"queued",selected_count:1,enriched_count:0,updated_count:0,skipped_count:0,failed_count:0,last_activity_id:null,started_at:null,updated_at:new Date().toISOString(),completed_at:null,next_resume_at:null,error_category:null});try{const started=await client.startEnrichment([activityId],1);setJob({job_id:started.job_id,status:started.status,selected_count:1,enriched_count:0,updated_count:0,skipped_count:0,failed_count:0,last_activity_id:null,started_at:null,updated_at:new Date().toISOString(),completed_at:null,next_resume_at:null,error_category:null});void poll(started.job_id)}catch{setJob(null);setMessage("No se pudo iniciar la actualización. Comprueba la conexión e inténtalo de nuevo.")}};
 const back=new URLSearchParams(window.location.search).get("return")??"",backUrl=`/activities${back?`?${back}`:""}`;if(loading)return <div className="browse-state" aria-live="polite">Cargando resumen…</div>;if(error||!activity)return <div className="browse-state" role="alert"><h1>Actividad no encontrada</h1><p>No existe o no está disponible para este atleta.</p><AppLink className="button button--primary" to={backUrl}>Volver a actividades</AppLink></div>;
 const sport=displaySport(activity.sport_type),speed=formatSportSpeed(activity.sport_type,activity.average_speed_metres_per_second,activity.max_speed_metres_per_second),cadence=formatCadence(activity.sport_type,activity.average_cadence),setting=activity.trainer===null?"Sin datos":activity.trainer?"Rodillo":"Exterior";
 const primary:Metric[]=[{label:"Distancia",value:soft(formatDistance(activity.distance_metres,activity.sport_type))},{label:"Tiempo en movimiento",value:soft(formatDuration(activity.moving_time_seconds))},{label:"Tiempo total",value:soft(formatDuration(activity.elapsed_time_seconds))},{label:"Desnivel",value:soft(formatElevation(activity.elevation_metres))}];
 const performance:Metric[]=[{label:speed.averageLabel,value:soft(speed.averageValue),icon:"◷"},{label:speed.maximumLabel,value:soft(speed.maximumValue),icon:"↗"},{label:"Frecuencia cardiaca media",value:heart(activity.average_heart_rate),icon:"♥"},{label:"Frecuencia cardiaca máxima",value:heart(activity.max_heart_rate),icon:"♥"},{label:cadence.label,value:soft(cadence.value),icon:"↻"},{label:"Potencia media",value:soft(formatPower(activity.average_watts)),icon:"ϟ"},{label:"Potencia ponderada",value:soft(formatPower(activity.weighted_average_watts)),icon:"ϟ"}];
 const visibility=formatVisibility(activity.visibility),metadata:BadgeMetric[]=[{label:"Entrenador",value:soft(formatTrainer(activity.trainer)),icon:"●",tone:activity.trainer?"trainer":"outdoor"},{label:"Registro",value:soft(formatManual(activity.manual)),icon:activity.manual?"✎":"⚡",tone:"registration"},{label:"Tipo",value:soft(formatCommute(activity.commute)),icon:activity.commute?"◆":"◇",tone:"type"},{label:"Visibilidad",value:soft(visibility),icon:visibility==="Todos"||visibility==="Pública"?"◎":visibility==="Seguidores"?"◉":"▣",tone:"visibility"}];
 const active=job&&["queued","running"].includes(job.status);const details:Metric[]=[{label:"Calorías",value:number(activity.calories,"kcal")},{label:"Dispositivo",value:activity.device_name??"—"},{label:"Equipo",value:activity.gear_id??"—"},{label:"Temperatura media",value:number(activity.average_temperature_celsius,"°C")},{label:"Esfuerzo percibido",value:number(activity.perceived_exertion,"/ 10")},{label:"Suffer score",value:number(activity.suffer_score,"")},{label:"Trabajo total",value:activity.kilojoules!=null?number(activity.kilojoules,"kJ"):number(activity.total_work_joules,"J")},{label:"Potencia máxima",value:number(activity.max_watts,"W")}];
 return <article className={`activity-summary-page activity-summary-page--${activity.sport_type}`}><AppLink className="back-link" to={backUrl}>← Volver a actividades</AppLink><header className="activity-hero"><div className="activity-hero__decoration" aria-hidden="true">{sportIcon(activity.sport_type)}</div><span className="sport-pill"><span aria-hidden="true">{sportIcon(activity.sport_type)} </span>{sport}</span><h1>{activity.name}</h1><p className="activity-hero__summary"><span aria-hidden="true">{sportIcon(activity.sport_type)}</span> {sport} · {setting} · {soft(formatDistance(activity.distance_metres,activity.sport_type))} · {formatCompactDuration(activity.moving_time_seconds)}</p><time dateTime={activity.start_time}>{formatActivityDateLine(activity.start_time,activity.athlete_timezone)}</time></header><aside className="summary-notice" aria-labelledby="summary-notice-title"><p id="summary-notice-title">Estás viendo el resumen importado de esta actividad.</p><p>En próximas versiones podrás consultar:</p><ul><li>mapa</li><li>vueltas</li><li>streams</li><li>análisis avanzado</li></ul></aside><MetricSection title="Resumen" items={primary} primary/><MetricSection title="Rendimiento" items={performance}/><MetadataSection items={metadata}/><section className="summary-section enrichment-section" aria-labelledby="enrichment-title"><div className="enrichment-heading"><div><h2 id="enrichment-title">Detalles de Strava</h2><p>Estado: <strong>{statusLabel(job?.status??activity.enrichment_status)}</strong>{activity.enriched_at&&<> · <time dateTime={activity.enriched_at}>{new Intl.DateTimeFormat("es-ES",{dateStyle:"medium",timeStyle:"short"}).format(new Date(activity.enriched_at))}</time></>}</p></div><button className="button button--primary" type="button" onClick={start} disabled={Boolean(active)||!client.startEnrichment} aria-label="Actualizar detalles de esta actividad">{active&&<span className="button-spinner" aria-hidden="true"/>}{active?"Actualizando detalles…":job?.status==="retry_scheduled"?"Reanudar detalles":"Actualizar detalles"}</button></div>{message&&<p className={job?.status==="failed"?"enrichment-message enrichment-message--error":"enrichment-message"} role={job?.status==="failed"?"alert":"status"}>{message}</p>}{activity.provider_description&&<p className="activity-description">{activity.provider_description}</p>}<dl className="enriched-grid">{details.map(item=><div key={item.label}><dt>{item.label}</dt><dd><MetricValue value={item.value}/></dd></div>)}</dl></section><ActivityMetricsSection activityId={activityId} client={client}/><ActivityEvidenceSection activityId={activityId} sport={activity.sport_type} client={client}/></article>
}


