import { render,screen,waitFor } from "@testing-library/react";import userEvent from "@testing-library/user-event";import { beforeEach,describe,expect,it,vi } from "vitest";import type { ApiClient } from "../../services/apiClient";import type { ActivityDetail,ActivityPage } from "../../types/api";import { ActivitiesPage } from "./ActivitiesPage";import { ActivitySummaryPage } from "./ActivitySummaryPage";
const item={id:"a1",external_activity_id:"1",name:"Morning Run",sport_type:"running",start_time:"2026-07-14T06:00:00Z",athlete_timezone:"Europe/Madrid",distance_metres:8200,moving_time_seconds:2538,elapsed_time_seconds:2600,elevation_metres:74,average_heart_rate:145,average_watts:null,trainer:false,manual:false,visibility:"everyone"};const page:ActivityPage={total:21,limit:20,offset:0,items:[item]};
function client(overrides:Partial<ApiClient>={}):ApiClient{return {health:vi.fn(),stravaStatus:vi.fn(),activities:vi.fn(),latestImport:vi.fn(),startImport:vi.fn(),importStatus:vi.fn(),dashboardSummary:vi.fn(),dashboardTrends:vi.fn(),dashboardConsistency:vi.fn(),connectUrl:vi.fn(),browseActivities:vi.fn().mockResolvedValue(page),activityFilterOptions:vi.fn().mockResolvedValue({sport_types:["running"],visibility_values:["everyone"],minimum_activity_date:"2026-01-01",maximum_activity_date:"2026-07-14"}),activityDetail:vi.fn().mockResolvedValue({...item,max_heart_rate:null,average_speed_metres_per_second:null,max_speed_metres_per_second:null,average_cadence:null,weighted_average_watts:null,commute:null,created_at:"2026-07-14T06:00:00Z",updated_at:"2026-07-14T06:00:00Z"} satisfies ActivityDetail),...overrides} as ApiClient}
beforeEach(()=>window.history.replaceState({},"","/activities"));
describe("ActivitiesPage",()=>{
 it("renders Spanish results and filter form",async()=>{render(<ActivitiesPage client={client()}/>);expect(screen.getByRole("heading",{name:"Actividades"})).toBeInTheDocument();expect(await screen.findByText("Morning Run")).toBeInTheDocument();expect(screen.getByLabelText("Buscar")).toBeInTheDocument()});
 it("applies filters explicitly and synchronizes the URL",async()=>{const c=client();render(<ActivitiesPage client={c}/>);await screen.findByText("Morning Run");await userEvent.type(screen.getByLabelText("Buscar"),"morning");expect(c.browseActivities).toHaveBeenCalledTimes(1);await userEvent.click(screen.getByRole("button",{name:"Aplicar filtros"}));await waitFor(()=>expect(window.location.search).toContain("search=morning"));await waitFor(()=>expect(c.browseActivities).toHaveBeenCalledTimes(2))});
 it("clears URL filters",async()=>{window.history.replaceState({},"","/activities?search=run");render(<ActivitiesPage client={client()}/>);await screen.findByText("Morning Run");await userEvent.click(screen.getByRole("button",{name:"Limpiar filtros"}));expect(window.location.search).toBe("")});
 it("paginates and disables unavailable controls",async()=>{const c=client();render(<ActivitiesPage client={c}/>);await screen.findByText(/1–20 de 21/);expect(screen.getByRole("button",{name:"Anterior"})).toBeDisabled();await userEvent.click(screen.getByRole("button",{name:"Siguiente"}));await waitFor(()=>expect(window.location.search).toContain("page=2"))});
 it("renders empty and safe error states",async()=>{const {unmount}=render(<ActivitiesPage client={client({browseActivities:vi.fn().mockResolvedValue({...page,total:0,items:[]})})}/>);expect(await screen.findByText("Sin resultados")).toBeInTheDocument();unmount();render(<ActivitiesPage client={client({browseActivities:vi.fn().mockRejectedValue(new Error("secret"))})}/>);expect(await screen.findByRole("alert")).toHaveTextContent("No se han podido cargar")});
});
describe("ActivitySummaryPage",()=>{it("renders safe detail, unavailable values and back link",async()=>{render(<ActivitySummaryPage activityId="a1" client={client()}/>);expect(await screen.findByRole("heading",{name:"Morning Run"})).toBeInTheDocument();expect(screen.getByText("Estás viendo el resumen importado de esta actividad.")).toBeInTheDocument();expect(screen.getByText("mapa")).toBeInTheDocument();expect(screen.getAllByLabelText("Sin datos").length).toBeGreaterThan(0);expect(screen.getByRole("link",{name:/volver a actividades/i})).toHaveAttribute("href","/activities")});it("handles a missing detail safely",async()=>{render(<ActivitySummaryPage activityId="missing" client={client({activityDetail:vi.fn().mockRejectedValue(new Error("404"))})}/>);expect(await screen.findByRole("heading",{name:"Actividad no encontrada"})).toBeInTheDocument()})});

it("orders localized summary sections and formats cycling performance",async()=>{const detail={...item,sport_type:"cycling",average_speed_metres_per_second:10,max_speed_metres_per_second:15,average_cadence:88,average_watts:221.6,weighted_average_watts:240.4,max_heart_rate:180,trainer:true,manual:true,commute:false,visibility:"only_me",created_at:"2026-07-14T06:00:00Z",updated_at:"2026-07-14T06:00:00Z"} as ActivityDetail;render(<ActivitySummaryPage activityId="a1" client={client({activityDetail:vi.fn().mockResolvedValue(detail)})}/>);await screen.findByRole("heading",{name:"Morning Run"});const headings=screen.getAllByRole("heading",{level:2}).map(x=>x.textContent);expect(headings).toEqual(["Resumen","Rendimiento","Información de la actividad","Detalles de Strava","Métricas factuales","Evidencia de la actividad"]);const metric=(text:string)=>screen.getByText((_,element)=>element?.tagName==="DD"&&element.textContent===text);expect(metric("36,0 km/h")).toBeInTheDocument();expect(metric("54,0 km/h")).toBeInTheDocument();expect(metric("222 W")).toBeInTheDocument();expect(metric("240 W")).toBeInTheDocument();expect(metric("88 rpm")).toBeInTheDocument();expect(screen.getByText("Sí, rodillo")).toHaveClass("metadata-badge");expect(screen.getByText("Registrada manualmente")).toBeInTheDocument();expect(screen.getByText("Actividad deportiva")).toBeInTheDocument();expect(screen.getByText("Solo yo")).toBeInTheDocument()});

it("renders the compact localized hero summary and friendly roadmap message",async()=>{const detail={...item,sport_type:"cycling",distance_metres:33100,moving_time_seconds:3840,trainer:false,average_speed_metres_per_second:8.5,max_speed_metres_per_second:12,average_cadence:null,weighted_average_watts:null,max_heart_rate:null,commute:false,created_at:"2026-07-14T06:00:00Z",updated_at:"2026-07-14T06:00:00Z"} as ActivityDetail;render(<ActivitySummaryPage activityId="a1" client={client({activityDetail:vi.fn().mockResolvedValue(detail)})}/>);expect(await screen.findByText("Ciclismo · Exterior · 33,1 km · 1 h 04 min")).toBeInTheDocument();expect(screen.getByText(/Martes · 14 jul 2026 · 08:00/)).toBeInTheDocument();expect(screen.getByText("En próximas versiones podrás consultar:")).toBeInTheDocument();for(const text of ["mapa","vueltas","streams","análisis avanzado"])expect(screen.getByText(text)).toBeInTheDocument()});


describe("activity detail enrichment",()=>{
 const enriched={...item,max_heart_rate:null,average_speed_metres_per_second:null,max_speed_metres_per_second:null,average_cadence:null,weighted_average_watts:null,commute:null,created_at:"2026-07-14T06:00:00Z",updated_at:"2026-07-14T06:00:00Z",provider_description:"Salida larga controlada",calories:612.5,device_name:"Edge 840",gear_id:"b123",suffer_score:72,perceived_exertion:6,total_work_joules:184000,kilojoules:184,average_temperature_celsius:18.4,max_watts:522,enriched_at:"2026-07-15T08:00:00Z",enrichment_status:"succeeded"} as ActivityDetail;
 it("renders enriched provider fields with Spanish labels and safe missing values",async()=>{render(<ActivitySummaryPage activityId="a1" client={client({activityDetail:vi.fn().mockResolvedValue(enriched),startEnrichment:vi.fn()})}/>);expect(await screen.findByRole("heading",{name:"Detalles de Strava"})).toBeInTheDocument();expect(screen.getByText("Salida larga controlada")).toBeInTheDocument();expect(screen.getByText("Edge 840")).toBeInTheDocument();expect(screen.getByText((_,element)=>element?.tagName==="DD"&&element.textContent==="612,5 kcal")).toBeInTheDocument();expect(screen.getByText((_,element)=>element?.tagName==="DD"&&element.textContent==="522 W")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Actualizar detalles de esta actividad"})).toBeEnabled()});
 it("disables the button while updating and refreshes after success",async()=>{let release:(value:{job_id:string;status:"queued"})=>void=()=>{};const startEnrichment=vi.fn(()=>new Promise<{job_id:string;status:"queued"}>(resolve=>{release=resolve}));const detail=vi.fn().mockResolvedValue(enriched);const enrichmentStatus=vi.fn().mockResolvedValue({job_id:"j1",status:"succeeded",selected_count:1,enriched_count:1,updated_count:1,skipped_count:0,failed_count:0,last_activity_id:"a1",started_at:null,updated_at:"2026-07-15T08:00:00Z",completed_at:"2026-07-15T08:00:00Z",next_resume_at:null,error_category:null});render(<ActivitySummaryPage activityId="a1" client={client({activityDetail:detail,startEnrichment,enrichmentStatus})}/>);const button=await screen.findByRole("button",{name:"Actualizar detalles de esta actividad"});await userEvent.click(button);expect(screen.getByRole("button",{name:"Actualizar detalles de esta actividad"})).toBeDisabled();release({job_id:"j1",status:"queued"});expect(await screen.findByText("Detalles actualizados correctamente.")).toBeInTheDocument();await waitFor(()=>expect(detail).toHaveBeenCalledTimes(2))});
 it("shows paused and safe start-error states",async()=>{const paused=client({startEnrichment:vi.fn().mockResolvedValue({job_id:"j1",status:"queued"}),enrichmentStatus:vi.fn().mockResolvedValue({job_id:"j1",status:"retry_scheduled",selected_count:1,enriched_count:0,updated_count:0,skipped_count:0,failed_count:0,last_activity_id:null,started_at:null,updated_at:"2026-07-15T08:00:00Z",completed_at:null,next_resume_at:"2026-07-15T08:15:00Z",error_category:"rate_limited"})});const {unmount}=render(<ActivitySummaryPage activityId="a1" client={paused}/>);await userEvent.click(await screen.findByRole("button",{name:"Actualizar detalles de esta actividad"}));expect(await screen.findByText("Actualización en pausa. Puedes reanudarla de forma segura.")).toBeInTheDocument();unmount();render(<ActivitySummaryPage activityId="a1" client={client({startEnrichment:vi.fn().mockRejectedValue(new Error("provider secret"))})}/>);await userEvent.click(await screen.findByRole("button",{name:"Actualizar detalles de esta actividad"}));expect(await screen.findByText("No se pudo iniciar la actualización. Comprueba la conexión e inténtalo de nuevo.")).toHaveAttribute("role","status")});
});




