import {useEffect,useState} from "react";
import type {ApiClient} from "../../services/apiClient";
import type {ActivityEvidence,EvidenceLap} from "../../types/api";
import {formatCadence,formatDistance,formatDuration,formatElevation,formatPower,formatSportSpeed,softValue} from "../../utils/format";
import {EvidenceStreamChart} from "./EvidenceStreamChart";
const tabs=[{key:"velocity_smooth",label:"Ritmo o velocidad"},{key:"heartrate",label:"Frecuencia cardíaca"},{key:"watts",label:"Potencia"},{key:"cadence",label:"Cadencia"},{key:"altitude",label:"Altitud"}] as const;
const soft=(value:string)=>softValue(value);
function lapSpeed(lap:EvidenceLap,sport:string){return formatSportSpeed(sport,lap.average_speed_metres_per_second,lap.maximum_speed_metres_per_second).averageValue}
function Laps({items,sport}:{items:EvidenceLap[];sport:string}){if(!items.length)return <p className="evidence-empty">No hay vueltas disponibles.</p>;return <div className="laps-scroll"><table className="laps-table"><caption>Vueltas importadas</caption><thead><tr><th>Vuelta</th><th>Distancia</th><th>Tiempo en movimiento</th><th>{sport==="cycling"?"Velocidad":"Ritmo"}</th><th>FC media</th><th>Cadencia</th><th>Potencia</th><th>Desnivel</th></tr></thead><tbody>{items.map(x=><tr key={x.lap_index}><th data-label="Vuelta">{x.lap_index}</th><td data-label="Distancia">{soft(formatDistance(x.distance_metres,sport))}</td><td data-label="Tiempo">{soft(formatDuration(x.moving_time_seconds))}</td><td data-label="Ritmo o velocidad">{soft(lapSpeed(x,sport))}</td><td data-label="FC media">{x.average_heart_rate==null?"—":`${Math.round(x.average_heart_rate)} ppm`}</td><td data-label="Cadencia">{formatCadence(sport,x.average_cadence).value}</td><td data-label="Potencia">{formatPower(x.average_watts)}</td><td data-label="Desnivel">{formatElevation(x.elevation_metres)}</td></tr>)}</tbody></table></div>}
function EvidenceChart({evidence}:{evidence:ActivityEvidence}){const available=tabs.filter(x=>evidence.streams[x.key]),[selected,setSelected]=useState(available[0]?.key??"");useEffect(()=>{if(!evidence.streams[selected])setSelected(available[0]?.key??"")},[evidence,selected]);const stream=evidence.streams[selected];if(!available.length)return <p className="evidence-empty">No hay streams gráficos disponibles.</p>;return <div className="evidence-chart"><div className="evidence-chart__heading"><h3>{tabs.find(tab=>tab.key===selected)?.label} durante la actividad</h3></div><div className="chart-tabs" role="tablist" aria-label="Métrica del gráfico">{available.map(tab=><button key={tab.key} role="tab" aria-selected={selected===tab.key} onClick={()=>setSelected(tab.key)}>{tab.label}</button>)}</div>{stream&&<><EvidenceStreamChart evidence={evidence} streamKey={selected} stream={stream}/>{stream.downsampled&&<p className="downsample-notice">Datos reducidos de {stream.original_sample_count} a {stream.sample_count} muestras, conservando inicio, final y alineación.</p>}</>}</div>}
export function ActivityEvidenceSection({activityId,sport,client}:{activityId:string;sport:string;client:ApiClient}){const [evidence,setEvidence]=useState<ActivityEvidence|null>(null),[loading,setLoading]=useState(false),[message,setMessage]=useState<string|null>(null),[location,setLocation]=useState(false);const refresh=()=>client.activityEvidence?.(activityId).then(setEvidence).catch(()=>setEvidence(null));useEffect(()=>{void refresh()},[activityId,client]);const poll=async(id:string)=>{if(!client.evidenceStatus)return;try{const job=await client.evidenceStatus(id);if(["succeeded","partially_succeeded"].includes(job.status)){await refresh();setLoading(false);setMessage(job.status==="succeeded"?"Evidencia cargada correctamente.":"Evidencia cargada parcialmente.");return}if(job.status==="retry_scheduled"){setLoading(false);setMessage("Carga en pausa. Puedes reanudarla de forma segura.");return}if(["failed","cancelled"].includes(job.status)){setLoading(false);setMessage("No se pudo cargar la evidencia. Inténtalo más tarde.");return}window.setTimeout(()=>void poll(id),500)}catch{setLoading(false);setMessage("No se pudo consultar la carga de evidencia.")}};const load=async()=>{if(!client.startEvidence)return;setLoading(true);setMessage(null);try{const job=await client.startEvidence([activityId],location);void poll(job.job_id)}catch{setLoading(false);setMessage("No se pudo iniciar la carga de evidencia.")}};return <section className="summary-section activity-evidence" aria-labelledby="activity-evidence-title"><div className="evidence-heading"><div><h2 id="activity-evidence-title">Evidencia de la actividad</h2><p>Vueltas y series registradas, sin análisis ni interpretación.</p></div><button className="button button--primary" onClick={load} disabled={loading||!client.startEvidence}>{loading&&<span className="button-spinner" aria-hidden="true"/>}{loading?"Cargando evidencia…":"Cargar vueltas y gráficos"}</button></div>{evidence?.route.retention_enabled&&<label className="location-option"><input type="checkbox" checked={location} onChange={e=>setLocation(e.target.checked)}/> Incluir ubicación sensible para esta carga</label>}{evidence?.location_status==="privacy_disabled"&&<p className="privacy-state">Ruta no disponible: la retención de ubicación está desactivada.</p>}{message&&<p role="status" className="enrichment-message">{message}</p>}<h3>Vueltas</h3><Laps items={evidence?.laps??[]} sport={sport}/>{evidence?<EvidenceChart evidence={evidence}/>:<p className="evidence-empty">Carga la evidencia para ver streams disponibles.</p>}<h3>Ruta</h3><p className="route-placeholder">{evidence?.route.available&&evidence.route.retention_enabled?"Ruta disponible. La vista cartográfica queda diferida; se conserva únicamente la evidencia autorizada.":evidence?.location_status==="privacy_disabled"?"Ubicación no retenida por privacidad.":"Sin ruta disponible."}</p></section>}

