const states:Record<string,string>={available:"Disponible",partial:"Parcial",unavailable:"No disponible",not_applicable:"No aplicable"};
const sources:Record<string,string>={activity_summary:"Resumen de actividad",activity_detail:"Detalle de actividad",laps:"Vueltas",streams:"Streams",stream_time:"Tiempo",stream_distance:"Distancia",stream_heartrate:"Frecuencia cardiaca",stream_watts:"Potencia",stream_cadence:"Cadencia",stream_altitude:"Altitud",stream_velocity_smooth:"Velocidad"};
const reasons:Record<string,string>={missing_stream:"No hay datos disponibles",no_evidence:"Sin evidencia suficiente",unsupported_activity_type:"No aplicable a este tipo de actividad",insufficient_samples:"Muestras insuficientes",incompatible_lengths:"Datos no alineados",zero_distance:"Distancia cero",zero_duration:"Duración cero",malformed_values:"Datos no válidos",privacy_restricted:"Restringido por privacidad",provider_unavailable:"Datos del proveedor no disponibles"};
export const metricStatus=(v:string)=>states[v]??"No disponible";
export const metricSource=(v:string|null)=>v?(sources[v]??v):"Sin fuente";
export const metricReason=(v:string|null)=>v?(reasons[v]??"Sin datos"):"Sin datos";
export function formatMetricTime(value:number|null){if(value===null||!Number.isFinite(value)||value<0)return "No disponible";const s=Math.round(value),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return h?`${h}:${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`:`${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`}
export function formatMetricDistance(value:number|null){if(value===null||!Number.isFinite(value)||value<0)return "No disponible";const km=value/1000;return new Intl.NumberFormat("es-ES",{maximumFractionDigits:2,minimumFractionDigits:km<1?1:2}).format(km<1?value:km)+` ${km<1?"m":"km"}`}
export function formatMetricNumber(value:number|null,unit:string,decimals=0){if(value===null||!Number.isFinite(value))return "No disponible";return `${new Intl.NumberFormat("es-ES",{maximumFractionDigits:decimals}).format(value)} ${unit}`}
export function formatMetricValue(key:string,value:number|null,unit:string|null){if(key.includes("time"))return formatMetricTime(value);if(key==="distance")return formatMetricDistance(value);if(key.includes("speed"))return formatMetricNumber(value===null?null:value*3.6,"km/h",2);if(key.includes("heart_rate"))return formatMetricNumber(value,"ppm",key.startsWith("max")?0:1);if(key.includes("power"))return formatMetricNumber(value,"W",0);if(key.includes("cadence"))return formatMetricNumber(value,"rpm",0);if(key==="lap_count")return formatMetricNumber(value,"vueltas",0);if(key==="stream_sample_count")return value===null||!Number.isFinite(value)?"No disponible":Math.round(value).toString().replace(/\B(?=(\d{3})+(?!\d))/g,".")+" muestras";return formatMetricNumber(value,unit??"",2)}
