from __future__ import annotations
from uuid import UUID
from sqlalchemy import select
from sqlalchemy.orm import Session
from app.db.models import ActivityEvidenceState,ActivityLap,ActivityRouteEvidence,ActivityStream,AthleteProfile,CompletedActivity
SUPPORTED=("time","distance","heartrate","watts","cadence","altitude","velocity_smooth")
class ActivityEvidenceQuery:
 def __init__(self,session:Session,*,location_enabled:bool,max_samples:int):self.s=session;self.location=location_enabled;self.max=max_samples
 def for_user(self,user_id:UUID,activity_id:UUID):
  activity=self.s.scalar(select(CompletedActivity).join(AthleteProfile).where(CompletedActivity.id==activity_id,AthleteProfile.user_id==user_id,AthleteProfile.deleted_at.is_(None),CompletedActivity.deleted_at.is_(None),CompletedActivity.provider_deleted_at.is_(None)))
  if not activity:return None
  laps=list(self.s.scalars(select(ActivityLap).where(ActivityLap.completed_activity_id==activity_id).order_by(ActivityLap.lap_index)).all());allowed=SUPPORTED+(("latlng",) if self.location else ());streams=list(self.s.scalars(select(ActivityStream).where(ActivityStream.completed_activity_id==activity_id,ActivityStream.stream_type.in_(allowed)).order_by(ActivityStream.stream_type)).all());state=self.s.scalar(select(ActivityEvidenceState).where(ActivityEvidenceState.completed_activity_id==activity_id));route=self.s.scalar(select(ActivityRouteEvidence).where(ActivityRouteEvidence.completed_activity_id==activity_id)) if self.location else None
  present={x.stream_type for x in streams};missing=[x for x in SUPPORTED if x not in present];fetched=max((x for x in ((state.laps_fetched_at if state else None),(state.streams_fetched_at if state else None)) if x),default=None)
  return {"activity_id":activity.id,"sport_type":activity.sport,"laps":[{"lap_index":x.lap_index,"name":x.name,"start_date":x.start_date,"elapsed_time_seconds":x.elapsed_time_seconds,"moving_time_seconds":x.moving_time_seconds,"distance_metres":x.distance_metres,"elevation_metres":x.elevation_metres,"average_speed_metres_per_second":x.average_speed_metres_per_second,"maximum_speed_metres_per_second":x.maximum_speed_metres_per_second,"average_heart_rate":x.average_heart_rate,"maximum_heart_rate":x.maximum_heart_rate,"average_cadence":x.average_cadence,"average_watts":x.average_watts} for x in laps],"streams":{x.stream_type:{"stream_type":x.stream_type,"values":x.values[:self.max],"sample_count":min(x.sample_count,self.max),"original_sample_count":x.original_sample_count,"downsampled":x.original_sample_count>x.sample_count,"series_type":x.original_series_type} for x in streams if x.stream_type!="latlng"},"route":{"available":bool(route and route.available),"retention_enabled":self.location,"sample_count":route.sample_count if route else 0,"polyline":route.summary_polyline if route and self.location else None},"fetched_at":fetched,"partial":bool(state and state.status=="partial"),"missing_streams":missing,"location_status":"available" if self.location and route and route.available else "unavailable" if self.location else "privacy_disabled"}
