import {useEffect,useState} from "react";
import type {ApiClient} from "../../services/apiClient";import type {ManualStrengthSession,ManualStrengthSessionCreate} from "../../types/manualStrength";import {ManualStrengthForm} from "./ManualStrengthForm";import {ManualStrengthSessionCard} from "./ManualStrengthSessionCard";
export function ManualStrengthPage({client,canCreate=true,canUpdate=true,canDelete=true,canRecalculate=true}:{client:ApiClient;canCreate?:boolean;canUpdate?:boolean;canDelete?:boolean;canRecalculate?:boolean}){
 const [sessions,setSessions]=useState<ManualStrengthSession[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[editing,setEditing]=useState<ManualStrengthSession|null|undefined>(),[saving,setSaving]=useState(false),[busy,setBusy]=useState<string|null>(null),[deleting,setDeleting]=useState<ManualStrengthSession|null>(null);
 useEffect(()=>{client.listManualStrengthSessions?.().then(setSessions).catch(()=>setError("No se han podido cargar los entrenamientos de fuerza.")).finally(()=>setLoading(false))},[client]);
 async function save(value:ManualStrengthSessionCreate){if(!client.createManualStrengthSession||!client.updateManualStrengthSession)return;setSaving(true);setError("");try{const result=editing?await client.updateManualStrengthSession(editing.id,value):await client.createManualStrengthSession(value);setSessions(current=>editing?current.map(item=>item.id===result.id?result:item):[result,...current]);setEditing(undefined);setMessage(editing?"Entrenamiento actualizado.":"Entrenamiento añadido.")}catch{setError("No se ha podido guardar el entrenamiento.")}finally{setSaving(false)}}
 async function recalculate(session:ManualStrengthSession){if(!client.recalculateManualStrengthLoad)return;setBusy(session.id);try{const load=await client.recalculateManualStrengthLoad(session.id);setSessions(current=>current.map(item=>item.id===session.id?{...item,training_load:load}:item));setMessage("Carga recalculada.")}catch{setError("No se ha podido recalcular la carga.")}finally{setBusy(null)}}
 async function remove(){if(!deleting||!client.deleteManualStrengthSession)return;setBusy(deleting.id);try{await client.deleteManualStrengthSession(deleting.id);setSessions(current=>current.filter(item=>item.id!==deleting.id));setDeleting(null);setMessage("Entrenamiento eliminado.")}catch{setError("No se ha podido eliminar el entrenamiento.")}finally{setBusy(null)}}
 return <article className="manual-strength-page"><header className="strength-page-header"><div><p>Actividades</p><h1>Fuerza</h1><span>Registra tus sesiones y consulta su carga de entrenamiento.</span></div>{canCreate&&<button className="button button--primary" onClick={()=>setEditing(null)}>Añadir entrenamiento de fuerza</button>}</header><div aria-live="polite">{message}</div>{!canCreate&&!canUpdate&&!canDelete&&<p>Acceso de solo lectura</p>}{error&&<p role="alert" className="training-load-state--error">{error}</p>}{loading?<p role="status">Cargando entrenamientos de fuerza…</p>:sessions.length?<section className="strength-list">{sessions.map(session=><ManualStrengthSessionCard key={session.id} session={session} busy={busy===session.id} onEdit={canUpdate?()=>setEditing(session):undefined} onRecalculate={canRecalculate?()=>void recalculate(session):undefined} onDelete={canDelete?()=>setDeleting(session):undefined}/>)}</section>:<section className="strength-empty"><h2>Todavía no has registrado entrenamientos de fuerza.</h2>{canCreate&&<button className="button button--primary" onClick={()=>setEditing(null)}>Añadir entrenamiento de fuerza</button>}</section>}{editing!==undefined&&<ManualStrengthForm session={editing} saving={saving} error={error} onCancel={()=>setEditing(undefined)} onSave={value=>void save(value)}/>} {deleting&&<div className="modal-backdrop"><section className="strength-confirm" role="alertdialog" aria-modal="true" aria-labelledby="delete-strength-title"><h2 id="delete-strength-title">Eliminar entrenamiento de fuerza</h2><p>Esta acción eliminará la sesión y actualizará las estadísticas de carga.</p><button onClick={()=>setDeleting(null)}>Cancelar</button><button className="button button--danger" disabled={busy===deleting.id} onClick={()=>void remove()}>Eliminar</button></section></div>}</article>
}
