"""Add factual activity laps, streams, and route evidence.

Revision ID: 0005_activity_evidence
Revises: 0004_strava_activity_detail
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0005_activity_evidence";down_revision="0004_strava_activity_detail";branch_labels=None;depends_on=None
json_type=sa.JSON().with_variant(postgresql.JSONB(),"postgresql")
def upgrade()->None:
 op.create_table("activity_laps",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("completed_activity_id",sa.Uuid(),sa.ForeignKey("completed_activities.id",ondelete="CASCADE"),nullable=False),sa.Column("provider_lap_id",sa.String(255)),sa.Column("provider_index",sa.Integer(),nullable=False),sa.Column("lap_index",sa.Integer(),nullable=False),sa.Column("name",sa.String(300)),sa.Column("start_date",sa.DateTime(timezone=True)),sa.Column("elapsed_time_seconds",sa.Integer()),sa.Column("moving_time_seconds",sa.Integer()),sa.Column("distance_metres",sa.Float()),sa.Column("elevation_metres",sa.Float()),sa.Column("average_speed_metres_per_second",sa.Float()),sa.Column("maximum_speed_metres_per_second",sa.Float()),sa.Column("average_heart_rate",sa.Float()),sa.Column("maximum_heart_rate",sa.Float()),sa.Column("average_cadence",sa.Float()),sa.Column("average_watts",sa.Float()),sa.Column("lap_type",sa.String(64)),sa.Column("pace_zone",sa.Integer()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("completed_activity_id","provider_index",name="uq_activity_lap_activity_provider_index"))
 op.create_index("ix_activity_laps_completed_activity_id","activity_laps",["completed_activity_id"])
 op.create_table("activity_streams",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("completed_activity_id",sa.Uuid(),sa.ForeignKey("completed_activities.id",ondelete="CASCADE"),nullable=False),sa.Column("stream_type",sa.String(32),nullable=False),sa.Column("original_resolution",sa.String(32)),sa.Column("original_series_type",sa.String(32)),sa.Column("original_sample_count",sa.Integer(),nullable=False),sa.Column("sample_count",sa.Integer(),nullable=False),sa.Column("values",json_type,nullable=False),sa.Column("fetched_at",sa.DateTime(timezone=True),nullable=False),sa.Column("source_updated_at",sa.DateTime(timezone=True)),sa.Column("retention_class",sa.String(32),nullable=False),sa.Column("checksum",sa.String(64),nullable=False),sa.Column("version",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("completed_activity_id","stream_type",name="uq_activity_stream_activity_type"))
 op.create_index("ix_activity_streams_completed_activity_id","activity_streams",["completed_activity_id"]);op.create_index("ix_activity_streams_fetched_at","activity_streams",["fetched_at"])
 op.create_table("activity_route_evidence",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("completed_activity_id",sa.Uuid(),sa.ForeignKey("completed_activities.id",ondelete="CASCADE"),nullable=False),sa.Column("available",sa.Boolean(),nullable=False),sa.Column("summary_polyline",sa.Text()),sa.Column("sample_count",sa.Integer(),nullable=False),sa.Column("fetched_at",sa.DateTime(timezone=True),nullable=False),sa.Column("source_updated_at",sa.DateTime(timezone=True)),sa.Column("retention_class",sa.String(32),nullable=False),sa.Column("checksum",sa.String(64)),sa.Column("version",sa.Integer(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("completed_activity_id",name="uq_activity_route_activity"))
 op.create_index("ix_activity_route_evidence_completed_activity_id","activity_route_evidence",["completed_activity_id"])
 op.create_table("activity_evidence_states",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("completed_activity_id",sa.Uuid(),sa.ForeignKey("completed_activities.id",ondelete="CASCADE"),nullable=False),sa.Column("laps_fetched_at",sa.DateTime(timezone=True)),sa.Column("streams_fetched_at",sa.DateTime(timezone=True)),sa.Column("source_updated_at",sa.DateTime(timezone=True)),sa.Column("status",sa.String(32)),sa.Column("error_category",sa.String(100)),sa.Column("location_retained",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("completed_activity_id",name="uq_activity_evidence_state_activity"))
 op.create_index("ix_activity_evidence_states_completed_activity_id","activity_evidence_states",["completed_activity_id"])
 op.create_index("uq_sync_jobs_active_strava_evidence","sync_jobs",["integration_account_id"],unique=True,postgresql_where=sa.text("job_type = 'strava_activity_evidence' AND status IN ('queued','running','retry_scheduled')"),sqlite_where=sa.text("job_type = 'strava_activity_evidence' AND status IN ('queued','running','retry_scheduled')"))
def downgrade()->None:
 op.drop_index("uq_sync_jobs_active_strava_evidence",table_name="sync_jobs");op.drop_table("activity_evidence_states");op.drop_table("activity_route_evidence");op.drop_table("activity_streams");op.drop_table("activity_laps")
