from alembic import op
import sqlalchemy as sa
revision='0010_training_load_aggregates'; down_revision='0009_activity_training_load'; branch_labels=None; depends_on=None
def upgrade():
 common=lambda: [sa.Column('id',sa.Uuid(),primary_key=True),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('athlete_profile_id',sa.Uuid(),sa.ForeignKey('athlete_profiles.id',ondelete='CASCADE'),nullable=False),sa.Column('timezone_name',sa.String(64),nullable=False),sa.Column('source_load_algorithm_version',sa.String(32),nullable=False),sa.Column('aggregation_algorithm_version',sa.String(32),nullable=False),sa.Column('total_load',sa.Numeric(14,2),nullable=False),sa.Column('activity_count',sa.Integer(),nullable=False),sa.Column('loaded_activity_count',sa.Integer(),nullable=False),sa.Column('null_load_activity_count',sa.Integer(),nullable=False),sa.Column('total_duration_seconds',sa.Numeric(14,2),nullable=False),sa.Column('coverage',sa.String(24),nullable=False),sa.Column('quality',sa.String(24),nullable=False),sa.Column('warnings',sa.JSON(),nullable=False),sa.Column('activity_ids',sa.JSON(),nullable=False),sa.Column('calculated_at',sa.DateTime(timezone=True),nullable=False)]
 op.create_table('athlete_daily_training_loads',*common(),sa.Column('local_date',sa.Date(),nullable=False),sa.UniqueConstraint('athlete_profile_id','local_date','timezone_name','source_load_algorithm_version','aggregation_algorithm_version',name='uq_daily_load_configuration'))
 op.create_index('ix_daily_load_athlete_date','athlete_daily_training_loads',['athlete_profile_id','local_date'])
 op.create_table('athlete_weekly_training_loads',*common(),sa.Column('iso_year',sa.Integer(),nullable=False),sa.Column('iso_week',sa.Integer(),nullable=False),sa.Column('week_start_date',sa.Date(),nullable=False),sa.Column('week_end_date',sa.Date(),nullable=False),sa.UniqueConstraint('athlete_profile_id','iso_year','iso_week','timezone_name','source_load_algorithm_version','aggregation_algorithm_version',name='uq_weekly_load_configuration'))
 op.create_index('ix_weekly_load_athlete_date','athlete_weekly_training_loads',['athlete_profile_id','week_start_date'])
def downgrade():
 op.drop_index('ix_weekly_load_athlete_date',table_name='athlete_weekly_training_loads');op.drop_index('ix_daily_load_athlete_date',table_name='athlete_daily_training_loads');op.drop_table('athlete_weekly_training_loads');op.drop_table('athlete_daily_training_loads')
