"""Training planning persistence foundation."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0022_training_planning_base";down_revision="0021_user_account_plan";branch_labels=None;depends_on=None

def upgrade()->None:
 op.create_table("competition_goals",
  sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("athlete_profile_id",sa.Uuid(),sa.ForeignKey("athlete_profiles.id",ondelete="CASCADE"),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("event_date",sa.Date(),nullable=False),sa.Column("event_start_time",sa.Time(),nullable=True),sa.Column("timezone",sa.String(64),nullable=False),sa.Column("event_category",sa.String(24),nullable=False),sa.Column("event_format",sa.String(32),nullable=False),sa.Column("priority",sa.String(1),nullable=False),sa.Column("distance_m",sa.Integer()),sa.Column("swim_distance_m",sa.Integer()),sa.Column("bike_distance_m",sa.Integer()),sa.Column("run_distance_m",sa.Integer()),sa.Column("target_finish_time_seconds",sa.Integer()),sa.Column("notes",sa.Text()),sa.Column("status",sa.String(16),nullable=False),sa.Column("created_by_user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),
  sa.CheckConstraint("priority IN ('A','B','C')",name="competition_goal_priority_valid"),sa.CheckConstraint("status IN ('active','completed','cancelled')",name="competition_goal_status_valid"),sa.CheckConstraint("event_category IN ('triathlon','running','cycling','swimming')",name="competition_goal_category_valid"),sa.CheckConstraint("target_finish_time_seconds IS NULL OR target_finish_time_seconds > 0",name="competition_goal_target_time_positive"),sa.CheckConstraint("distance_m IS NULL OR distance_m >= 0",name="competition_goal_distance_nonnegative"),sa.CheckConstraint("swim_distance_m IS NULL OR swim_distance_m >= 0",name="competition_goal_swim_nonnegative"),sa.CheckConstraint("bike_distance_m IS NULL OR bike_distance_m >= 0",name="competition_goal_bike_nonnegative"),sa.CheckConstraint("run_distance_m IS NULL OR run_distance_m >= 0",name="competition_goal_run_nonnegative"))
 op.create_index("ix_competition_goals_athlete_date","competition_goals",["athlete_profile_id","event_date"]);op.create_index("ix_competition_goals_creator","competition_goals",["created_by_user_id"])
 op.create_table("training_plans",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("athlete_profile_id",sa.Uuid(),sa.ForeignKey("athlete_profiles.id",ondelete="CASCADE"),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("start_date",sa.Date(),nullable=False),sa.Column("end_date",sa.Date(),nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("origin",sa.String(16),nullable=False),sa.Column("created_by_user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_via_role",sa.String(16)),sa.Column("algorithm_version",sa.String(64)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("start_date <= end_date",name="training_plan_dates_valid"),sa.CheckConstraint("status IN ('draft','active','completed','archived')",name="training_plan_status_valid"),sa.CheckConstraint("origin IN ('human','ai')",name="training_plan_origin_valid"),sa.CheckConstraint("created_via_role IS NULL OR created_via_role IN ('owner','athlete','coach')",name="training_plan_role_valid"))
 op.create_index("ix_training_plans_athlete_dates","training_plans",["athlete_profile_id","start_date","end_date"]);op.create_index("ix_training_plans_creator","training_plans",["created_by_user_id"])
 op.create_table("training_plan_goals",sa.Column("training_plan_id",sa.Uuid(),sa.ForeignKey("training_plans.id",ondelete="CASCADE"),primary_key=True),sa.Column("competition_goal_id",sa.Uuid(),sa.ForeignKey("competition_goals.id",ondelete="RESTRICT"),primary_key=True),sa.Column("relationship",sa.String(16),nullable=False),sa.CheckConstraint("relationship IN ('primary','supporting')",name="training_plan_goal_relationship_valid"),sa.UniqueConstraint("training_plan_id","competition_goal_id",name="uq_training_plan_goal_pair"))
 op.create_table("planned_training_sessions",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("athlete_profile_id",sa.Uuid(),sa.ForeignKey("athlete_profiles.id",ondelete="CASCADE"),nullable=False),sa.Column("training_plan_id",sa.Uuid(),sa.ForeignKey("training_plans.id",ondelete="SET NULL")),sa.Column("scheduled_date",sa.Date(),nullable=False),sa.Column("scheduled_start_time",sa.Time()),sa.Column("timezone",sa.String(64),nullable=False),sa.Column("sport",sa.String(24),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("description",sa.Text()),sa.Column("planned_duration_seconds",sa.Integer()),sa.Column("planned_distance_meters",sa.Integer()),sa.Column("status",sa.String(16),nullable=False),sa.Column("origin",sa.String(16),nullable=False),sa.Column("created_by_user_id",sa.Uuid(),sa.ForeignKey("users.id",ondelete="SET NULL")),sa.Column("created_via_role",sa.String(16)),sa.Column("algorithm_version",sa.String(64)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("status IN ('planned','completed','skipped','cancelled')",name="planned_session_status_valid"),sa.CheckConstraint("origin IN ('human','ai')",name="planned_session_origin_valid"),sa.CheckConstraint("created_via_role IS NULL OR created_via_role IN ('owner','athlete','coach')",name="planned_session_role_valid"),sa.CheckConstraint("planned_duration_seconds IS NULL OR planned_duration_seconds >= 0",name="planned_session_duration_nonnegative"),sa.CheckConstraint("planned_distance_meters IS NULL OR planned_distance_meters >= 0",name="planned_session_distance_nonnegative"))
 op.create_index("ix_planned_sessions_athlete_date","planned_training_sessions",["athlete_profile_id","scheduled_date"]);op.create_index("ix_planned_sessions_plan","planned_training_sessions",["training_plan_id"]);op.create_index("ix_planned_sessions_creator","planned_training_sessions",["created_by_user_id"])
 op.create_table("structured_workouts",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("planned_training_session_id",sa.Uuid(),sa.ForeignKey("planned_training_sessions.id",ondelete="CASCADE"),nullable=False),sa.Column("schema_version",sa.Integer(),nullable=False),sa.Column("definition",sa.JSON().with_variant(postgresql.JSONB(),"postgresql"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("schema_version = 1",name="structured_workout_schema_version_valid"),sa.UniqueConstraint("planned_training_session_id",name="uq_structured_workout_session"))

def downgrade()->None:
 op.drop_table("structured_workouts");op.drop_index("ix_planned_sessions_creator",table_name="planned_training_sessions");op.drop_index("ix_planned_sessions_plan",table_name="planned_training_sessions");op.drop_index("ix_planned_sessions_athlete_date",table_name="planned_training_sessions");op.drop_table("planned_training_sessions");op.drop_table("training_plan_goals");op.drop_index("ix_training_plans_creator",table_name="training_plans");op.drop_index("ix_training_plans_athlete_dates",table_name="training_plans");op.drop_table("training_plans");op.drop_index("ix_competition_goals_creator",table_name="competition_goals");op.drop_index("ix_competition_goals_athlete_date",table_name="competition_goals");op.drop_table("competition_goals")
