import {useCallback,useEffect,useMemo,useRef,useState,type FormEvent} from "react";
import {useAthleteContext} from "../../app/AthleteContext";
import {useAuth} from "../../app/AuthContext";
import {apiClient,type ApiClient} from "../../services/apiClient";
import {centimetersToMeters,displayHeight,displayWeight,feetAndInchesToMeters,poundsToKilograms} from "./athleteProfileFormat";
import type {AthleteProfile,AthleteProfileField,AthleteProfileUpdateRequest,UnitSystem} from "./athleteProfileTypes";

interface FormState{displayName:string;timezone:string;unitSystem:UnitSystem;birthYear:string;sex:string;heightPrimary:string;heightSecondary:string;weight:string}
const labels:Record<AthleteProfileField,string>={birth_year:"Año de nacimiento",sex_for_training_context:"Sexo para contexto deportivo",height_m:"Altura",weight_kg:"Peso"};
const same=(a:number|null,b:number|null)=>a===b||a!==null&&b!==null&&Math.abs(a-b)<0.0005;
const numberOrNull=(value:string)=>value.trim()===""?null:Number(value.replace(",","."));
function formFrom(profile:AthleteProfile):FormState{const height=displayHeight(profile.height_m,profile.unit_system);return {displayName:profile.display_name,timezone:profile.timezone,unitSystem:profile.unit_system,birthYear:profile.birth_year===null?"":String(profile.birth_year),sex:profile.sex_for_training_context??"",heightPrimary:height.primary,heightSecondary:height.secondary,weight:displayWeight(profile.weight_kg,profile.unit_system)}}
function canonicalHeight(form:FormState){const primary=numberOrNull(form.heightPrimary);if(primary===null)return null;if(!Number.isFinite(primary))return NaN;return form.unitSystem==="metric"?centimetersToMeters(primary):feetAndInchesToMeters(primary,numberOrNull(form.heightSecondary)??0)}
function canonicalWeight(form:FormState){const value=numberOrNull(form.weight);if(value===null||!Number.isFinite(value))return value;return form.unitSystem==="metric"?Math.round(value*1000)/1000:poundsToKilograms(value)}
function errorMessage(error:unknown){const value=error instanceof Error?error.message:"";if(value.includes("(403)"))return "No tienes permisos para editar este perfil deportivo.";if(value.includes("(422)"))return "Revisa los campos indicados: alguno de los valores no es válido.";return "No se ha podido conectar con el servidor. Inténtalo de nuevo."}

export function AthleteProfilePage({client=apiClient}:{client?:ApiClient}){
 const {activeAthlete,activeAthleteId,refreshContext,hasAthleteCapability}=useAthleteContext(),{refreshUser}=useAuth();
 const [profile,setProfile]=useState<AthleteProfile|null>(null),[form,setForm]=useState<FormState|null>(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState(""),[formError,setFormError]=useState("");
 const generation=useRef(0),mounted=useRef(true),canEdit=hasAthleteCapability("edit_athlete_profile");
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;generation.current++}},[]);
 const load=useCallback(async()=>{const current=++generation.current;setLoading(true);setLoadError(false);setProfile(null);setForm(null);setFeedback("");try{if(!activeAthleteId||!client.getAthleteProfile)throw new Error("athlete_profile_unavailable");const value=await client.getAthleteProfile();if(!mounted.current||current!==generation.current)return;setProfile(value);setForm(formFrom(value))}catch(error){if(!mounted.current||current!==generation.current||(error instanceof Error&&error.name==="AbortError"))return;if(error instanceof Error&&error.message.includes("(401)"))void refreshUser().catch(()=>undefined);else setLoadError(true)}finally{if(mounted.current&&current===generation.current)setLoading(false)}},[activeAthleteId,client,refreshUser]);
 useEffect(()=>{void load();return()=>{generation.current++}},[load]);
 const payload=useMemo<AthleteProfileUpdateRequest|null>(()=>{if(!profile||!form)return null;const next:AthleteProfileUpdateRequest={},birth=numberOrNull(form.birthYear),height=canonicalHeight(form),weight=canonicalWeight(form),sex=form.sex.trim()||null,presentation=formFrom({...profile,unit_system:form.unitSystem}),heightOnlyReformatted=form.unitSystem!==profile.unit_system&&form.heightPrimary===presentation.heightPrimary&&form.heightSecondary===presentation.heightSecondary,weightOnlyReformatted=form.unitSystem!==profile.unit_system&&form.weight===presentation.weight;if(form.displayName!==profile.display_name)next.display_name=form.displayName;if(form.timezone!==profile.timezone)next.timezone=form.timezone;if(form.unitSystem!==profile.unit_system)next.unit_system=form.unitSystem;if(!same(birth,profile.birth_year))next.birth_year=birth;if(sex!==profile.sex_for_training_context)next.sex_for_training_context=sex;if(!heightOnlyReformatted&&!same(height,profile.height_m))next.height_m=height;if(!weightOnlyReformatted&&!same(weight,profile.weight_kg))next.weight_kg=weight;return next},[profile,form]);
 const dirty=Boolean(payload&&Object.keys(payload).length);
 function update<K extends keyof FormState>(key:K,value:FormState[K]){setForm(current=>current?{...current,[key]:value}:current);setFeedback("");setFormError("")}
 function changeUnits(unit:UnitSystem){setForm(current=>{if(!current||current.unitSystem===unit)return current;const meters=canonicalHeight(current),kg=canonicalWeight(current),height=displayHeight(Number.isFinite(meters)?meters:null,unit);return {...current,unitSystem:unit,heightPrimary:height.primary,heightSecondary:height.secondary,weight:displayWeight(Number.isFinite(kg)?kg:null,unit)}});setFeedback("")}
 async function save(event:FormEvent){event.preventDefault();if(saving||!profile||!form||!payload||!dirty||!client.updateAthleteProfile)return;setFormError("");setFeedback("");const currentYear=new Date().getFullYear(),birth=numberOrNull(form.birthYear),height=canonicalHeight(form),weight=canonicalWeight(form);if(!form.displayName.trim())return setFormError("El nombre del atleta es obligatorio.");if(!form.timezone.trim())return setFormError("La zona horaria es obligatoria.");if(birth!==null&&(!Number.isInteger(birth)||birth<1900||birth>currentYear))return setFormError("Introduce un año de nacimiento válido.");if(height!==null&&(!Number.isFinite(height)||height<=0))return setFormError("Introduce una altura válida.");if(weight!==null&&(!Number.isFinite(weight)||weight<=0))return setFormError("Introduce un peso válido.");setSaving(true);try{const value=await client.updateAthleteProfile(payload);if(!mounted.current)return;setProfile(value);setForm(formFrom(value));setFeedback("Perfil deportivo actualizado correctamente.");if("display_name" in payload||"timezone" in payload||"unit_system" in payload)await refreshContext({preferredAthleteId:activeAthleteId??undefined})}catch(error){if(!mounted.current)return;if(error instanceof Error&&error.message.includes("(401)"))void refreshUser().catch(()=>undefined);else setFormError(errorMessage(error))}finally{if(mounted.current)setSaving(false)}}
 if(loading)return <section className="athlete-profile-state" role="status" aria-live="polite">Cargando perfil deportivo…</section>;
 if(loadError)return <section className="athlete-profile-state athlete-profile-state--error" role="alert"><h1>No se ha podido cargar el perfil deportivo.</h1><button className="button button--primary" type="button" onClick={()=>void load()}>Reintentar</button></section>;
 if(!profile||!form)return null;
 const minimal=profile.completeness.status==="minimal";
 return <div className="athlete-profile-page"><header className="athlete-profile-header"><p>CONFIGURACIÓN</p><h1>Perfil deportivo</h1><span>Datos básicos del atleta seleccionado utilizados como contexto para el entrenamiento.</span></header>
  <section className="athlete-profile-active" aria-label="Atleta activo"><span>Atleta activo</span><strong>{activeAthlete?.label??profile.display_name}</strong></section>
  <section className={`athlete-profile-completeness athlete-profile-completeness--${profile.completeness.status}`}><h2>{minimal?"Perfil deportivo básico":"Perfil deportivo completo"}</h2>{minimal&&<><p>Puedes completar algunos datos opcionales para aportar más contexto al entrenamiento.</p><p>Datos recomendados pendientes: {profile.completeness.missing_recommended_fields.map(field=>labels[field]).join(", ")}.</p></>}</section>
  {!canEdit&&<p className="athlete-profile-readonly" role="status">Modo solo lectura. No tienes permisos para editar este perfil deportivo.</p>}
  <form className="athlete-profile-form" onSubmit={save}><div className="athlete-profile-grid">
   <label>Nombre del atleta<input value={form.displayName} required maxLength={200} disabled={!canEdit||saving} onChange={event=>update("displayName",event.target.value)}/></label>
   <label>Zona horaria<input value={form.timezone} required maxLength={64} disabled={!canEdit||saving} onChange={event=>update("timezone",event.target.value)}/></label>
   <label>Sistema de unidades<select value={form.unitSystem} disabled={!canEdit||saving} onChange={event=>changeUnits(event.target.value as UnitSystem)}><option value="metric">Métrico</option><option value="imperial">Imperial</option></select></label>
   <label>Año de nacimiento<input type="number" min={1900} max={new Date().getFullYear()} value={form.birthYear} disabled={!canEdit||saving} onChange={event=>update("birthYear",event.target.value)}/></label>
   <label className="athlete-profile-wide">Sexo para contexto deportivo <span>(opcional)</span><input value={form.sex} maxLength={32} disabled={!canEdit||saving} aria-describedby="sex-help" onChange={event=>update("sex",event.target.value)}/><small id="sex-help">Dato opcional reservado para contexto deportivo. Actualmente no modifica los cálculos de entrenamiento.</small></label>
   {form.unitSystem==="metric"?<label>Altura (cm)<input type="number" step="0.1" value={form.heightPrimary} disabled={!canEdit||saving} onChange={event=>update("heightPrimary",event.target.value)}/></label>:<fieldset><legend>Altura</legend><label>Pies<input type="number" min="0" step="1" value={form.heightPrimary} disabled={!canEdit||saving} onChange={event=>update("heightPrimary",event.target.value)}/></label><label>Pulgadas<input type="number" min="0" max="11" step="1" value={form.heightSecondary} disabled={!canEdit||saving} onChange={event=>update("heightSecondary",event.target.value)}/></label></fieldset>}
   <label>Peso ({form.unitSystem==="metric"?"kg":"lb"})<input type="number" step="0.1" value={form.weight} disabled={!canEdit||saving} onChange={event=>update("weight",event.target.value)}/></label>
  </div><div className={formError?"athlete-profile-feedback athlete-profile-feedback--error":"athlete-profile-feedback"} role={formError?"alert":"status"} aria-live="polite">{formError||feedback}</div>{canEdit&&<button className="button button--primary" type="submit" disabled={!dirty||saving}>{saving?"Guardando…":"Guardar cambios"}</button>}</form>
 </div>
}
