import {StrictMode} from "react";
import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {describe,expect,it,vi} from "vitest";
import {AthleteContextProvider,useAthleteContext} from "../../app/AthleteContext";
import {AuthProvider,useAuth} from "../../app/AuthContext";
import type {ApiClient} from "../../services/apiClient";
import type {AthleteProfile} from "./athleteProfileTypes";
import {AthleteProfilePage} from "./AthleteProfilePage";

const profile=(id="a",name="Carlos",overrides:Partial<AthleteProfile>={}):AthleteProfile=>({id,display_name:name,timezone:"Europe/Madrid",unit_system:"metric",birth_year:null,sex_for_training_context:null,height_m:1.78,weight_kg:73.5,updated_at:"2026-08-12T10:00:00Z",completeness:{status:"minimal",missing_recommended_fields:["birth_year","sex_for_training_context"]},...overrides});
const session={user:{id:"user",display_name:"Carlos Cuenta",email:"c@example.test"},athletes:[{athlete_id:"a",label:"Carlos",role:"owner",is_default:true,capabilities:["read_athlete_data","edit_athlete_profile"]},{athlete_id:"b",label:"Jenny",role:"owner",is_default:false,capabilities:["read_athlete_data","edit_athlete_profile"]}],selected_athlete_id:"a",selection_required:false};
function client(overrides:Partial<ApiClient>={}):ApiClient{return {authMe:vi.fn().mockResolvedValue({...session.user,authentication_mode:"session"}),login:vi.fn(),logout:vi.fn(),sessionContext:vi.fn().mockResolvedValue(session),getAthleteProfile:vi.fn().mockResolvedValue(profile()),updateAthleteProfile:vi.fn().mockImplementation(async input=>profile("a",input.display_name??"Carlos",{...input})),...overrides} as unknown as ApiClient}
function Identity(){const {user}=useAuth();return <span>Cuenta {user?.display_name}</span>}
function SwitchingPage({client}:{client:ApiClient}){const {activeAthleteId,selectAthlete}=useAthleteContext();return <><span>Activo {activeAthleteId}</span><button onClick={()=>selectAthlete("a")}>Cambiar a Carlos</button><button onClick={()=>selectAthlete("b")}>Cambiar a Jenny</button><AthleteProfilePage key={activeAthleteId} client={client}/></>}
function view(api:ApiClient,withSwitch=false){return render(<StrictMode><AuthProvider client={api}><Identity/><AthleteContextProvider client={api}>{withSwitch?<SwitchingPage client={api}/>:<AthleteProfilePage client={api}/>}</AthleteContextProvider></AuthProvider></StrictMode>)}
describe("AthleteProfilePage in StrictMode",()=>{
 it("shows loading and then the active athlete with backend values",async()=>{let release!:(value:AthleteProfile)=>void;const pending=new Promise<AthleteProfile>(resolve=>release=resolve),api=client({getAthleteProfile:vi.fn().mockReturnValue(pending)});view(api);expect(await screen.findByText("Cargando perfil deportivo…")).toBeInTheDocument();release(profile());expect(await screen.findByText("Carlos",{selector:"strong"})).toBeInTheDocument();expect(screen.getByLabelText("Altura (cm)")).toHaveValue(178);expect(screen.getByLabelText("Peso (kg)")).toHaveValue(73.5);expect(screen.getByRole("button",{name:"Guardar cambios"})).toBeDisabled()});
 it("sends a partial PATCH, refreshes the selector and keeps the User identity",async()=>{const api=client();view(api);const name=await screen.findByLabelText("Nombre del atleta");await userEvent.clear(name);await userEvent.type(name,"Jenny Ruiz Test");await userEvent.click(screen.getByRole("button",{name:"Guardar cambios"}));await waitFor(()=>expect(api.updateAthleteProfile).toHaveBeenCalledWith({display_name:"Jenny Ruiz Test"}));expect(await screen.findByText("Perfil deportivo actualizado correctamente.")).toBeInTheDocument();expect(vi.mocked(api.sessionContext!).mock.calls.length).toBeGreaterThanOrEqual(3);expect(screen.getByText("Cuenta Carlos Cuenta")).toBeInTheDocument()});
 it("sends explicit null when an optional field is cleared",async()=>{const api=client({getAthleteProfile:vi.fn().mockResolvedValue(profile("a","Carlos",{birth_year:1985}))});view(api);const year=await screen.findByLabelText("Año de nacimiento");await userEvent.clear(year);await userEvent.click(screen.getByRole("button",{name:"Guardar cambios"}));expect(api.updateAthleteProfile).toHaveBeenCalledWith({birth_year:null})});
 it("allows clearing canonical height and weight explicitly",async()=>{const api=client();view(api);await userEvent.clear(await screen.findByLabelText("Altura (cm)"));await userEvent.clear(screen.getByLabelText("Peso (kg)"));await userEvent.click(screen.getByRole("button",{name:"Guardar cambios"}));expect(api.updateAthleteProfile).toHaveBeenCalledWith({height_m:null,weight_kg:null})});
 it("renders a recoverable GET error",async()=>{const get=vi.fn().mockRejectedValueOnce(new Error("network")).mockResolvedValue(profile()),api=client({getAthleteProfile:get});view(api);await userEvent.click(await screen.findByRole("button",{name:"Reintentar"}));expect(await screen.findByLabelText("Nombre del atleta")).toHaveValue("Carlos")});
 it("keeps read-only memberships readable and blocks editing",async()=>{const readonly={...session,athletes:session.athletes.map(a=>({...a,capabilities:["read_athlete_data"]}))},api=client({sessionContext:vi.fn().mockResolvedValue(readonly)});view(api);expect(await screen.findByText(/Modo solo lectura/)).toBeInTheDocument();expect(screen.getByLabelText("Nombre del atleta")).toBeDisabled();expect(screen.queryByRole("button",{name:"Guardar cambios"})).not.toBeInTheDocument()});
 it("does not let a stale A response overwrite B",async()=>{let releaseA!:(value:AthleteProfile)=>void;const pendingA=new Promise<AthleteProfile>(resolve=>releaseA=resolve),get=vi.fn().mockReturnValueOnce(pendingA).mockResolvedValue(profile("b","Jenny",{height_m:null,weight_kg:null})),api=client({getAthleteProfile:get});view(api,true);await userEvent.click(await screen.findByRole("button",{name:"Cambiar a Jenny"}));expect(await screen.findByDisplayValue("Jenny")).toBeInTheDocument();releaseA(profile("a","Carlos tardío"));await Promise.resolve();expect(screen.queryByDisplayValue("Carlos tardío")).not.toBeInTheDocument()});
 it("discards dirty A values when switching to B",async()=>{const apiA=client();const first=view(apiA);const weight=await screen.findByLabelText("Peso (kg)");await userEvent.clear(weight);await userEvent.type(weight,"99");first.unmount();localStorage.clear();const sessionB={...session,selected_athlete_id:"b"};const apiB=client({sessionContext:vi.fn().mockResolvedValue(sessionB),getAthleteProfile:vi.fn().mockResolvedValue(profile("b","Jenny",{weight_kg:60}))});view(apiB);expect(await screen.findByLabelText("Peso (kg)")).toHaveValue(60);expect(apiA.updateAthleteProfile).not.toHaveBeenCalled()});
 it("switches presentation units without persisting canonical measurements",async()=>{const api=client();view(api);await userEvent.selectOptions(await screen.findByLabelText("Sistema de unidades"),"imperial");expect(screen.getByLabelText("Pies")).toHaveValue(5);expect(screen.getByLabelText("Pulgadas")).toHaveValue(10);expect(screen.getByLabelText("Peso (lb)")).toHaveValue(162);await userEvent.click(screen.getByRole("button",{name:"Guardar cambios"}));expect(api.updateAthleteProfile).toHaveBeenCalledWith({unit_system:"imperial"})});
 it("refreshes authentication after a 401",async()=>{const auth=vi.fn().mockResolvedValueOnce({...session.user,authentication_mode:"session"}).mockRejectedValue(new Error("expired")),api=client({authMe:auth,updateAthleteProfile:vi.fn().mockRejectedValue(new Error("TriCoach API request failed (401)"))});view(api);await userEvent.type(await screen.findByLabelText("Nombre del atleta")," X");await userEvent.click(screen.getByRole("button",{name:"Guardar cambios"}));await waitFor(()=>expect(auth.mock.calls.length).toBeGreaterThanOrEqual(2))});
 it.each([[new Error("TriCoach API request failed (403)"),"No tienes permisos"],[new Error("TriCoach API request failed (422)"),"Revisa los campos"],[new Error("network"),"No se ha podido conectar"]])("maps save errors safely",async(error,message)=>{const api=client({updateAthleteProfile:vi.fn().mockRejectedValue(error)});view(api);const input=await screen.findByLabelText("Nombre del atleta");await userEvent.type(input," X");await userEvent.click(screen.getByRole("button",{name:"Guardar cambios"}));expect(await screen.findByRole("alert")).toHaveTextContent(message)});
});
