import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {beforeEach,describe,expect,it,vi} from "vitest";
import {AuthProvider} from "../../app/AuthContext";
import type {ApiClient} from "../../services/apiClient";
import {AccountPage} from "./AccountPage";

const account={id:"user-1",email:"ana@example.test",display_name:"Ana",created_at:"2026-08-10T10:00:00Z",last_login_at:"2026-08-10T12:00:00Z"};
function client(overrides:Partial<ApiClient>={}):ApiClient{return {authMe:vi.fn().mockResolvedValue({id:"user-1",email:"ana@example.test",display_name:"Ana",authentication_mode:"session"}),login:vi.fn(),logout:vi.fn(),getAccount:vi.fn().mockResolvedValue(account),updateAccount:vi.fn().mockResolvedValue({...account,display_name:"Ana Nueva"}),changePassword:vi.fn().mockResolvedValue(undefined),...overrides} as ApiClient}
function renderPage(api=client()){return {api,...render(<AuthProvider client={api}><AccountPage client={api}/></AuthProvider>)}}
beforeEach(()=>window.history.replaceState({},"","/settings/account"));

describe("AccountPage",()=>{
 it("shows loading and then safe account information",async()=>{let resolve:(value:typeof account)=>void=()=>undefined;const api=client({getAccount:vi.fn(()=>new Promise<typeof account>(value=>{resolve=value}))});renderPage(api);expect(screen.getByRole("status")).toHaveTextContent("Cargando cuenta");resolve(account);expect(await screen.findByRole("heading",{name:"Cuenta"})).toBeVisible();expect(screen.getByText("ana@example.test")).toBeVisible();expect(screen.getAllByText("Ana").length).toBeGreaterThan(0);expect(screen.getByText("Solo lectura")).toBeVisible();expect(screen.queryByText("user-1")).not.toBeInTheDocument()});
 it("handles nullable values",async()=>{renderPage(client({getAccount:vi.fn().mockResolvedValue({...account,display_name:null,last_login_at:null})}));expect(await screen.findByText("No definido")).toBeVisible();expect(screen.getByText("Sin accesos registrados")).toBeVisible()});
 it("shows a safe load error and retries",async()=>{const getAccount=vi.fn().mockRejectedValueOnce(new Error("network")).mockResolvedValue(account);renderPage(client({getAccount}));expect(await screen.findByRole("alert")).toHaveTextContent("No se ha podido cargar");await userEvent.click(screen.getByRole("button",{name:"Reintentar"}));expect(await screen.findByRole("heading",{name:"Cuenta"})).toBeVisible();expect(getAccount).toHaveBeenCalledTimes(2)});
 it("updates only display_name and refreshes authenticated identity",async()=>{const api=client();renderPage(api);const input=await screen.findByLabelText("Nombre visible");await userEvent.clear(input);await userEvent.type(input,"  Ana   Nueva  ");await userEvent.click(screen.getByRole("button",{name:"Guardar nombre"}));await waitFor(()=>expect(api.updateAccount).toHaveBeenCalledWith({display_name:"  Ana   Nueva  "}));expect(api.authMe).toHaveBeenCalledTimes(2);expect(await screen.findByText("Nombre actualizado correctamente.")).toBeVisible();expect(input).toHaveValue("Ana Nueva")});
 it("sends null when clearing the name and preserves input on failure",async()=>{const updateAccount=vi.fn().mockRejectedValue(new Error("network"));const api=client({updateAccount});renderPage(api);const input=await screen.findByLabelText("Nombre visible");await userEvent.clear(input);await userEvent.click(screen.getByRole("button",{name:"Guardar nombre"}));expect(updateAccount).toHaveBeenCalledWith({display_name:null});expect(await screen.findByRole("alert")).toHaveTextContent("No se ha podido guardar");expect(input).toHaveValue("")});
 it("validates required password and mismatched confirmation",async()=>{renderPage();await screen.findByRole("heading",{name:"Cuenta"});await userEvent.click(screen.getByRole("button",{name:"Cambiar contraseña"}));expect(screen.getByRole("alert")).toHaveTextContent("contraseña actual");await userEvent.type(screen.getByLabelText("Contraseña actual"),"actual");await userEvent.type(screen.getByLabelText("Nueva contraseña"),"nueva segura 123");await userEvent.type(screen.getByLabelText("Confirmar nueva contraseña"),"diferente 1234");await userEvent.click(screen.getByRole("button",{name:"Cambiar contraseña"}));expect(screen.getByRole("alert")).toHaveTextContent("no coinciden")});
 it("submits only backend password fields, clears secrets and keeps session",async()=>{const api=client();renderPage(api);await screen.findByRole("heading",{name:"Cuenta"});for(const [label,value] of [["Contraseña actual","contraseña actual"],["Nueva contraseña","contraseña nueva segura"],["Confirmar nueva contraseña","contraseña nueva segura"]])await userEvent.type(screen.getByLabelText(label),value);await userEvent.click(screen.getByRole("button",{name:"Cambiar contraseña"}));await waitFor(()=>expect(api.changePassword).toHaveBeenCalledWith({current_password:"contraseña actual",new_password:"contraseña nueva segura"}));expect(screen.getByText("Contraseña actualizada correctamente.")).toBeVisible();expect(screen.getByLabelText("Contraseña actual")).toHaveValue("");expect(api.logout).not.toHaveBeenCalled();expect(window.location.pathname).toBe("/settings/account")});
 it.each([["current_password_invalid","La contraseña actual no es correcta."],["new_password_unchanged","La nueva contraseña debe ser diferente"]])("translates %s safely",async(code,text)=>{renderPage(client({changePassword:vi.fn().mockRejectedValue(new Error(`TriCoach API request failed (400): {\"code\":\"${code}\"}`))}));await screen.findByRole("heading",{name:"Cuenta"});await userEvent.type(screen.getByLabelText("Contraseña actual"),"actual segura 123");await userEvent.type(screen.getByLabelText("Nueva contraseña"),"nueva segura 123");await userEvent.type(screen.getByLabelText("Confirmar nueva contraseña"),"nueva segura 123");await userEvent.click(screen.getByRole("button",{name:"Cambiar contraseña"}));expect(await screen.findByRole("alert")).toHaveTextContent(text)});
});
