export function formatDuration(seconds:number|null):string { if(seconds===null)return "No disponible"; const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),r=seconds%60; return h>0?`${h}:${String(m).padStart(2,"0")}:${String(r).padStart(2,"0")}`:`${m}:${String(r).padStart(2,"0")}`; }
export function formatDistance(m:number|null,sport="other"):string { if(m===null)return "No disponible"; if(["swim","swimming"].includes(sport.toLowerCase())&&m<10000)return `${Math.round(m).toLocaleString("es-ES")} m`; return `${(m/1000).toLocaleString("es-ES",{minimumFractionDigits:1,maximumFractionDigits:1})} km`; }
export function formatElevation(m:number|null):string { return m===null?"No disponible":`${Math.round(m).toLocaleString("es-ES")} m`; }
export function formatDate(v:string|null,tz="UTC"):string { return !v?"Nunca":new Intl.DateTimeFormat("es-ES",{dateStyle:"medium",timeStyle:"short",timeZone:tz}).format(new Date(v)); }
const sports:Record<string,string>={run:"Carrera",running:"Carrera",ride:"Ciclismo",cycling:"Ciclismo",swim:"Natación",swimming:"Natación",walk:"Caminata",hike:"Senderismo",workout:"Entrenamiento",weighttraining:"Fuerza",virtualride:"Ciclismo virtual",virtualrun:"Carrera virtual",other:"Otro"};
export function displaySport(s:string):string{return sports[s.toLowerCase()]??"Otro";}
export function sportIcon(s:string):string{const i:Record<string,string>={run:"↗",running:"↗",virtualrun:"↗",ride:"◇",cycling:"◇",virtualride:"◇",swim:"≈",swimming:"≈",walk:"•",hike:"△",workout:"+",weighttraining:"+",other:"•"};return i[s.toLowerCase()]??"•";}
const statuses:Record<string,string>={succeeded:"Completada",queued:"En cola",running:"Sincronizando",paused:"Pausada",retry_scheduled:"Pausada",failed:"Error",cancelled:"Cancelada",not_started:"Sin iniciar",connected:"Conectado",disconnected:"Desconectado",partially_succeeded:"Completada parcialmente"};
export function displayStatus(s:string):string{return statuses[s]??"Sin iniciar";}
export function formatRelativeDate(v:string|null):string|null{if(!v)return null;const sec=Math.round((new Date(v).getTime()-Date.now())/1000),f=new Intl.RelativeTimeFormat("es-ES",{numeric:"auto"});if(Math.abs(sec)<60)return f.format(sec,"second");const min=Math.round(sec/60);if(Math.abs(min)<60)return f.format(min,"minute");const h=Math.round(min/60);if(Math.abs(h)<24)return f.format(h,"hour");const d=Math.round(h/24);return Math.abs(d)<=7?f.format(d,"day"):null;}
function validPositive(value:number|null|undefined):value is number{return typeof value==="number"&&Number.isFinite(value)&&value>0;}
function clock(totalSeconds:number):string{const rounded=Math.round(totalSeconds);return `${Math.floor(rounded/60)}:${String(rounded%60).padStart(2,"0")}`;}
export interface SpeedPresentation{averageLabel:string;maximumLabel:string;averageValue:string;maximumValue:string;}
export function formatSportSpeed(sport:string,average:number|null,maximum:number|null):SpeedPresentation{const n=sport.toLowerCase();if(["running","run","walking","walk","hike"].includes(n)){const p=(v:number|null)=>validPositive(v)?`${clock(1000/v)} min/km`:"No disponible";return{averageLabel:"Ritmo medio",maximumLabel:"Mejor ritmo",averageValue:p(average),maximumValue:p(maximum)}}if(["swimming","swim"].includes(n)){const p=(v:number|null)=>validPositive(v)?`${clock(100/v)} /100 m`:"No disponible";return{averageLabel:"Ritmo medio",maximumLabel:"Mejor ritmo",averageValue:p(average),maximumValue:p(maximum)}}const speed=(v:number|null)=>validPositive(v)?`${(v*3.6).toLocaleString("es-ES",{minimumFractionDigits:1,maximumFractionDigits:1})} km/h`:"No disponible";return{averageLabel:"Velocidad media",maximumLabel:"Velocidad máxima",averageValue:speed(average),maximumValue:speed(maximum)}}
export const POWER_UNIT="W" as const;
export function formatPower(value:number|null|undefined):string{return validPositive(value)?`${Math.round(value)} ${POWER_UNIT}`:"No disponible";}
export function formatCadence(sport:string,value:number|null|undefined):{label:string;value:string}{const n=sport.toLowerCase();if(["swimming","swim"].includes(n))return{label:"Cadencia de brazada",value:"No disponible"};if(!validPositive(value))return{label:"Cadencia media",value:"No disponible"};if(["running","run","walking","walk","hike"].includes(n))return{label:"Cadencia media",value:`${Math.round(value)} ppm`};if(["cycling","ride","virtualride"].includes(n))return{label:"Cadencia media",value:`${Math.round(value)} rpm`};return{label:"Cadencia media",value:"No disponible"}}
const visibilityLabels:Record<string,string>={everyone:"Todos",public:"Pública",followers_only:"Seguidores",followers:"Seguidores",follower_only:"Seguidores",only_me:"Solo yo",solo_yo:"Solo yo",private:"Privada"};
export function formatVisibility(value:string|null|undefined):string{return value?visibilityLabels[value.toLowerCase()]??"No disponible":"No disponible";}
export function formatTrainer(value:boolean|null|undefined):string{return value===null||value===undefined?"No disponible":value?"Sí, rodillo":"No, exterior";}
export function formatManual(value:boolean|null|undefined):string{return value===null||value===undefined?"No disponible":value?"Registrada manualmente":"Registrada automáticamente";}
export function formatCommute(value:boolean|null|undefined):string{return value===null||value===undefined?"No disponible":value?"Desplazamiento":"Actividad deportiva";}
export function formatCompactDuration(seconds:number|null|undefined):string{if(seconds===null||seconds===undefined||!Number.isFinite(seconds)||seconds<0)return "—";const total=Math.round(seconds),hours=Math.floor(total/3600),minutes=Math.floor((total%3600)/60);return hours>0?`${hours} h ${String(minutes).padStart(2,"0")} min`:`${minutes} min`;}
export function formatActivityDateLine(value:string,timezone="UTC"):string{const parts=new Intl.DateTimeFormat("es-ES",{weekday:"long",day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:timezone,hour12:false}).formatToParts(new Date(value));const get=(type:Intl.DateTimeFormatPartTypes)=>parts.find(x=>x.type===type)?.value??"";const weekday=get("weekday");return `${weekday.charAt(0).toUpperCase()+weekday.slice(1)} · ${get("day")} ${get("month")} ${get("year")} · ${get("hour")}:${get("minute")}`;}
export function softValue(value:string):string{return value==="No disponible"?"—":value;}
