import type {CompetitionGoal} from "../../types/planning";
import {localDate} from "./competitionLabels";
const months=["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"];
const weekdays=["L","M","X","J","V","S","D"];
export function daysInMonth(year:number,month:number){return new Date(year,month+1,0).getDate()}
export function mondayOffset(year:number,month:number){return (new Date(year,month,1).getDay()+6)%7}
export function AnnualCalendar({goals,year,onYearChange,onSelectDate}:{goals:CompetitionGoal[];year:number;onYearChange:(year:number)=>void;onSelectDate:(date:string)=>void}){
 const today=new Date().getFullYear();const grouped=new Map<string,CompetitionGoal[]>();goals.forEach(goal=>grouped.set(goal.event_date,[...(grouped.get(goal.event_date)??[]),goal]));
 return <section className="annual-calendar" aria-labelledby="annual-calendar-title"><header className="annual-calendar__header"><h2 id="annual-calendar-title">Año {year}</h2><div><button onClick={()=>onYearChange(year-1)} aria-label="Año anterior">←</button><button onClick={()=>onYearChange(today)}>Año actual</button><button onClick={()=>onYearChange(year+1)} aria-label="Año siguiente">→</button></div></header><div className="annual-calendar__months">{months.map((name,month)=><section className="year-month" key={name} aria-label={`${name} de ${year}`}><h3>{name}</h3><div className="year-month__grid" aria-hidden="true">{weekdays.map((day,index)=><span key={index}>{day}</span>)}</div><div className="year-month__grid">{Array.from({length:mondayOffset(year,month)},(_,index)=><span key={`blank-${index}`}/>) }{Array.from({length:daysInMonth(year,month)},(_,index)=>{const day=index+1,date=`${year}-${String(month+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`,count=grouped.get(date)?.length??0,label=new Intl.DateTimeFormat("es-ES",{dateStyle:"long"}).format(localDate(date));return count?<button key={date} className="calendar-day calendar-day--goal" onClick={()=>onSelectDate(date)} aria-label={`${label}, ${count} ${count===1?"objetivo":"objetivos"}`}><span>{day}</span><strong>{count}</strong></button>:<span className="calendar-day" key={date}>{day}</span>})}</div></section>)}</div></section>
}
