import {useEffect,useRef,useState,type FormEvent} from "react";
import type {ApiClient} from "../../services/apiClient";
import type {CompetitionCategory,CompetitionGoal,CompetitionGoalCreate,CompetitionPriority} from "../../types/planning";

type Form={name:string;eventDate:string;category:CompetitionCategory;format:string;priority:CompetitionPriority;targetTime:string;notes:string;distanceKm:string;swimKm:string;bikeKm:string;runKm:string};
const empty:Form={name:"",eventDate:"",category:"running",format:"10k",priority:"A",targetTime:"",notes:"",distanceKm:"",swimKm:"",bikeKm:"",runKm:""};
const categoryLabels:Record<CompetitionCategory,string>={triathlon:"Triatlón",running:"Carrera",cycling:"Ciclismo",swimming:"Natación"};
const formats:Record<CompetitionCategory,{value:string;label:string;distances:Partial<CompetitionGoalCreate>}[]>={triathlon:[{value:"sprint",label:"Sprint",distances:{swim_distance_m:750,bike_distance_m:20000,run_distance_m:5000}},{value:"olympic",label:"Olímpico",distances:{swim_distance_m:1500,bike_distance_m:40000,run_distance_m:10000}},{value:"70.3",label:"70.3 / Media distancia",distances:{swim_distance_m:1900,bike_distance_m:90000,run_distance_m:21100}},{value:"ironman",label:"Ironman / Larga distancia",distances:{swim_distance_m:3800,bike_distance_m:180000,run_distance_m:42200}},{value:"custom",label:"Custom",distances:{}}],running:[{value:"5k",label:"5K",distances:{distance_m:5000}},{value:"10k",label:"10K",distances:{distance_m:10000}},{value:"half_marathon",label:"Media maratón",distances:{distance_m:21097}},{value:"marathon",label:"Maratón",distances:{distance_m:42195}},{value:"custom",label:"Custom",distances:{}}],cycling:[{value:"custom",label:"Distancia personalizada",distances:{}}],swimming:[{value:"custom",label:"Distancia personalizada",distances:{}}]};
function seconds(value:string){if(!value.trim())return null;const parts=value.split(":").map(Number);if(parts.length!==3||parts.some(x=>!Number.isInteger(x)||x<0)||parts[1]>59||parts[2]>59)return NaN;return parts[0]*3600+parts[1]*60+parts[2]}
function humanTime(value:number|null){if(value===null)return null;const h=Math.floor(value/3600),m=Math.floor(value%3600/60),s=value%60;return `${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
export function CalendarPage({client,canManage,athleteName,athleteId}:{client:ApiClient;canManage:boolean;athleteName?:string;athleteId?:string|null}){
 const [goals,setGoals]=useState<CompetitionGoal[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[form,setForm]=useState<Form>(empty),[editing,setEditing]=useState<string|null>(null),[saving,setSaving]=useState(false),[feedback,setFeedback]=useState("");const generation=useRef(0);
 const load=async()=>{const current=++generation.current;setLoading(true);setError("");try{const value=await client.competitionGoals?.();if(current===generation.current)setGoals(value??[])}catch{if(current===generation.current)setError("No se han podido cargar los objetivos.")}finally{if(current===generation.current)setLoading(false)}};
 useEffect(()=>{setGoals([]);setOpen(false);setEditing(null);void load();return()=>{generation.current++}},[client,athleteId]);
 const category=(value:CompetitionCategory)=>setForm(x=>({...x,category:value,format:formats[value][0].value}));
 const submit=async(event:FormEvent)=>{event.preventDefault();const target=seconds(form.targetTime);if(Number.isNaN(target)){setError("Introduce el objetivo de tiempo como h:mm:ss.");return}const preset=formats[form.category].find(x=>x.value===form.format)!;const custom=form.format==="custom"?(form.category==="triathlon"?{swim_distance_m:Math.round(Number(form.swimKm)*1000),bike_distance_m:Math.round(Number(form.bikeKm)*1000),run_distance_m:Math.round(Number(form.runKm)*1000)}:{distance_m:Math.round(Number(form.distanceKm)*1000)}):{};const payload:CompetitionGoalCreate={name:form.name.trim(),event_date:form.eventDate,event_category:form.category,event_format:form.format,priority:form.priority,target_finish_time_seconds:target,notes:form.notes.trim()||null,...preset.distances,...custom};setSaving(true);setError("");try{if(editing)await client.updateCompetitionGoal?.(editing,payload);else await client.createCompetitionGoal?.(payload);setOpen(false);setEditing(null);setForm(empty);setFeedback(editing?"Objetivo actualizado.":"Objetivo añadido.");await load()}catch{setError("No se ha podido guardar el objetivo.")}finally{setSaving(false)}};
 const edit=(goal:CompetitionGoal)=>{setEditing(goal.id);setForm({name:goal.name,eventDate:goal.event_date,category:goal.event_category,format:goal.event_format,priority:goal.priority,targetTime:humanTime(goal.target_finish_time_seconds)??"",notes:goal.notes??"",distanceKm:goal.distance_m===null?"":String(goal.distance_m/1000),swimKm:goal.swim_distance_m===null?"":String(goal.swim_distance_m/1000),bikeKm:goal.bike_distance_m===null?"":String(goal.bike_distance_m/1000),runKm:goal.run_distance_m===null?"":String(goal.run_distance_m/1000)});setOpen(true);setFeedback("")};
 const cancel=async(goal:CompetitionGoal)=>{if(!confirm(`¿Cancelar ${goal.name}?`))return;setError("");try{await client.deleteCompetitionGoal?.(goal.id);setFeedback("Objetivo cancelado.");await load()}catch{setError("No se ha podido cancelar el objetivo.")}};
 return <section className="calendar-page" aria-labelledby="calendar-title"><header className="calendar-header"><div><p className="eyebrow">PLANIFICACIÓN</p><h1 id="calendar-title">Calendario</h1><p>Próximas competiciones y objetivos de temporada.</p></div>{canManage&&<button className="button button--primary" onClick={()=>{setEditing(null);setForm(empty);setOpen(true)}}>+ Añadir objetivo</button>}</header>
 {feedback&&<p role="status" className="success-banner">{feedback}</p>}{error&&<div role="alert" className="error-banner"><span>{error}</span><button onClick={()=>void load()}>Reintentar</button></div>}
 {open&&canManage&&<form className="goal-form" onSubmit={submit}><fieldset><legend>{editing?"Editar objetivo":"Nuevo objetivo de competición"}</legend><label>Nombre<input required value={form.name} onChange={e=>setForm(x=>({...x,name:e.target.value}))}/></label><label>Fecha<input required type="date" value={form.eventDate} onChange={e=>setForm(x=>({...x,eventDate:e.target.value}))}/></label><label>Tipo de competición<select value={form.category} onChange={e=>category(e.target.value as CompetitionCategory)}>{Object.entries(categoryLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Formato/distancia<select value={form.format} onChange={e=>setForm(x=>({...x,format:e.target.value}))}>{formats[form.category].map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>{form.format==="custom"&&(form.category==="triathlon"?<div className="custom-distances"><label>Natación (km)<input required type="number" min="0.001" step="0.001" value={form.swimKm} onChange={e=>setForm(x=>({...x,swimKm:e.target.value}))}/></label><label>Ciclismo (km)<input required type="number" min="0.001" step="0.001" value={form.bikeKm} onChange={e=>setForm(x=>({...x,bikeKm:e.target.value}))}/></label><label>Carrera (km)<input required type="number" min="0.001" step="0.001" value={form.runKm} onChange={e=>setForm(x=>({...x,runKm:e.target.value}))}/></label></div>:<label>Distancia (km)<input required type="number" min="0.001" step="0.001" value={form.distanceKm} onChange={e=>setForm(x=>({...x,distanceKm:e.target.value}))}/></label>)}<fieldset className="priority-field"><legend>Prioridad</legend>{(["A","B","C"] as const).map(x=><label key={x}><input type="radio" name="priority" value={x} checked={form.priority===x} onChange={()=>setForm(v=>({...v,priority:x}))}/>{x}</label>)}<p>A — objetivo principal · B — objetivo importante · C — prueba secundaria o preparatoria</p></fieldset><label>Objetivo de tiempo opcional<input placeholder="5:15:00" value={form.targetTime} onChange={e=>setForm(x=>({...x,targetTime:e.target.value}))}/></label><label>Notas opcionales<textarea value={form.notes} onChange={e=>setForm(x=>({...x,notes:e.target.value}))}/></label><div className="goal-form__actions"><button className="button button--primary" disabled={saving}>{saving?"Guardando…":"Guardar objetivo"}</button><button type="button" className="button" onClick={()=>setOpen(false)}>Cancelar</button></div></fieldset></form>}
 {loading?<p className="loading-state">Cargando objetivos…</p>:goals.length===0?<div className="empty-state"><h2>{canManage?"Todavía no tienes objetivos de competición.":"Este atleta todavía no tiene objetivos de competición."}</h2>{canManage&&<p>Añade tu primera carrera para empezar a preparar tu temporada.</p>}</div>:<div className="goal-list" aria-label="Objetivos de competición">{goals.map(goal=><article className="goal-card" key={goal.id}><time dateTime={goal.event_date}>{new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(`${goal.event_date}T12:00:00Z`))}</time><div><span className={`priority-badge priority-badge--${goal.priority}`}>OBJETIVO {goal.priority}</span><h2>{goal.name}</h2><p>{categoryLabels[goal.event_category]} · {formats[goal.event_category].find(x=>x.value===goal.event_format)?.label??goal.event_format}</p>{goal.target_finish_time_seconds&&<p>Objetivo {humanTime(goal.target_finish_time_seconds)}</p>}</div>{canManage&&<div className="goal-card__actions"><button onClick={()=>edit(goal)}>Editar objetivo</button><button onClick={()=>void cancel(goal)}>Cancelar objetivo</button></div>}</article>)}</div>}
 {!canManage&&goals.length>0&&<p className="read-only-note">Puedes consultar los objetivos de {athleteName??"este atleta"} en modo solo lectura.</p>}</section>
}
