import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {describe,expect,it,vi} from "vitest";
import type {ApiClient} from "../../services/apiClient";
import type {CompetitionGoal} from "../../types/planning";
import {CalendarPage} from "./CalendarPage";
const goal:CompetitionGoal={id:"goal-1",athlete_profile_id:"athlete-a",name:"IRONMAN 70.3 Valencia",event_date:"2027-04-19",event_start_time:null,timezone:"Europe/Madrid",event_category:"triathlon",event_format:"70.3",priority:"A",distance_m:null,swim_distance_m:1900,bike_distance_m:90000,run_distance_m:21100,target_finish_time_seconds:18900,notes:null,status:"active",created_by_user_id:"user-1",created_at:"2026-08-15T10:00:00Z",updated_at:"2026-08-15T10:00:00Z"};
function client(goals:CompetitionGoal[]=[]):ApiClient{return {competitionGoals:vi.fn().mockResolvedValue(goals),createCompetitionGoal:vi.fn().mockResolvedValue(goal),updateCompetitionGoal:vi.fn().mockResolvedValue(goal),deleteCompetitionGoal:vi.fn().mockResolvedValue(undefined)} as unknown as ApiClient}
describe("Calendar competition goals",()=>{
 it("shows athlete empty state and accessible creation CTA with A/B/C explanation",async()=>{const api=client();render(<CalendarPage client={api} canManage athleteId="a"/>);expect(await screen.findByText("Todavía no tienes objetivos de competición.")).toBeVisible();await userEvent.click(screen.getByRole("button",{name:/Añadir objetivo/}));expect(screen.getByRole("group",{name:"Nuevo objetivo de competición"})).toBeVisible();expect(screen.getByText(/A — objetivo principal/)).toBeVisible()});
 it("creates and renders an objective with human target time",async()=>{const api=client();render(<CalendarPage client={api} canManage athleteId="a"/>);await screen.findByText("Todavía no tienes objetivos de competición.");await userEvent.click(screen.getByRole("button",{name:/Añadir objetivo/}));await userEvent.type(screen.getByLabelText("Nombre"),"IRONMAN 70.3 Valencia");await userEvent.type(screen.getByLabelText("Fecha"),"2027-04-19");await userEvent.selectOptions(screen.getByLabelText("Tipo de competición"),"triathlon");await userEvent.selectOptions(screen.getByLabelText("Formato/distancia"),"70.3");await userEvent.type(screen.getByLabelText("Objetivo de tiempo opcional"),"5:15:00");await userEvent.click(screen.getByRole("button",{name:"Guardar objetivo"}));expect(api.createCompetitionGoal).toHaveBeenCalledWith(expect.objectContaining({event_category:"triathlon",target_finish_time_seconds:18900,swim_distance_m:1900}));expect(vi.mocked(api.createCompetitionGoal!).mock.calls[0][0]).not.toHaveProperty("athlete_profile_id");await waitFor(()=>expect(api.competitionGoals).toHaveBeenCalledTimes(2))});
 it("shows goals read-only to coach without management actions",async()=>{render(<CalendarPage client={client([goal])} canManage={false} athleteName="CARLOS2" athleteId="b"/>);expect(await screen.findByText(goal.name)).toBeVisible();expect(screen.getByText("Objetivo 5:15:00")).toBeVisible();expect(screen.queryByRole("button",{name:/Añadir objetivo/})).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"Editar objetivo"})).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"Cancelar objetivo"})).not.toBeInTheDocument();expect(screen.getByText(/CARLOS2.*solo lectura/)).toBeVisible()});
 it("edits and cancels using the current goal id",async()=>{vi.spyOn(window,"confirm").mockReturnValue(true);const api=client([goal]);render(<CalendarPage client={api} canManage athleteId="a"/>);await userEvent.click(await screen.findByRole("button",{name:"Editar objetivo"}));await userEvent.click(screen.getByRole("button",{name:"Guardar objetivo"}));expect(api.updateCompetitionGoal).toHaveBeenCalledWith("goal-1",expect.any(Object));await userEvent.click(await screen.findByRole("button",{name:"Cancelar objetivo"}));expect(api.deleteCompetitionGoal).toHaveBeenCalledWith("goal-1")});
 it("covers error retry and reloads on athlete switch without stale rows",async()=>{const api=client([goal]);vi.mocked(api.competitionGoals!).mockRejectedValueOnce(new Error("offline")).mockResolvedValueOnce([]).mockResolvedValueOnce([]);const view=render(<CalendarPage client={api} canManage athleteId="a"/>);expect(await screen.findByRole("alert")).toHaveTextContent("No se han podido cargar");await userEvent.click(screen.getByRole("button",{name:"Reintentar"}));expect(await screen.findByText("Todavía no tienes objetivos de competición.")).toBeVisible();view.rerender(<CalendarPage client={api} canManage={false} athleteId="b"/>);expect(await screen.findByText("Este atleta todavía no tiene objetivos de competición.")).toBeVisible();expect(screen.queryByText(goal.name)).not.toBeInTheDocument()});
});
