import {useEffect,useRef,useState,type FormEvent} from "react";
import type {ApiClient} from "../../services/apiClient";
import type {CatalogEvent,CatalogProvider,CatalogSearchFilters,CompetitionCategory,WebCompetitionSearchResult} from "../../types/planning";
import {categoryLabels,segmentLabels} from "./competitionLabels";

export interface ManualGoalPrefill {name:string;category?:CompetitionCategory;sourceProvider:"tavily";sourceUrl:string}

export function CompetitionCatalogSearch({client,onImported,onManualGoal}:{client:ApiClient;onImported:()=>Promise<void>;onManualGoal?:(value:ManualGoalPrefill)=>void}){
 const [providers,setProviders]=useState<CatalogProvider[]>([]),[filters,setFilters]=useState<CatalogSearchFilters>({}),[structured,setStructured]=useState<CatalogEvent[]|null>(null),[web,setWeb]=useState<WebCompetitionSearchResult[]|null>(null),[hasMore,setHasMore]=useState(false),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[error,setError]=useState(""),[moreError,setMoreError]=useState(""),[importing,setImporting]=useState("");const generation=useRef(0);
 useEffect(()=>{const current=++generation.current;client.competitionCatalogProviders?.().then(value=>{if(current===generation.current){const configured=value.filter(item=>item.configured);setProviders(value);setFilters(old=>({...old,provider:old.provider||configured[0]?.provider||""}))}}).catch(()=>{if(current===generation.current)setError("No se ha podido consultar el catálogo.")}).finally(()=>{if(current===generation.current)setLoading(false)});return()=>{generation.current++}},[client]);
 const configured=providers.filter(item=>item.configured),selected=providers.find(item=>item.provider===filters.provider);
 const changeProvider=(provider:string)=>{generation.current++;setFilters(value=>({...value,provider}));setStructured(null);setWeb(null);setHasMore(false);setError("");setMoreError("")};
 const submit=async(event:FormEvent)=>{event.preventDefault();const current=++generation.current;setLoading(true);setError("");setMoreError("");setStructured(null);setWeb(null);try{if(selected?.search_mode==="web"){const value=await client.searchWebCompetitions?.(filters,"initial");if(current===generation.current){setWeb(value?.results??[]);setHasMore(Boolean(value?.has_more))}}else{const value=await client.searchCompetitionCatalog?.(filters);if(current===generation.current)setStructured(value??[])}}catch{if(current===generation.current)setError("No se ha podido realizar la búsqueda.")}finally{if(current===generation.current)setLoading(false)}};
 const loadMore=async()=>{const current=++generation.current;setLoadingMore(true);setMoreError("");try{const value=await client.searchWebCompetitions?.(filters,"more");if(current===generation.current){setWeb(value?.results??[]);setHasMore(Boolean(value?.has_more))}}catch{if(current===generation.current)setMoreError("No se han podido cargar más resultados.")}finally{if(current===generation.current)setLoadingMore(false)}};
 const importEvent=async(item:CatalogEvent)=>{setImporting(item.external_id);setError("");try{await client.importCompetitionGoal?.(item.provider,item.external_id,"B");await onImported();setStructured(current=>current?.filter(row=>row.provider!==item.provider||row.external_id!==item.external_id)??null)}catch(error){setError(error instanceof Error&&error.message.includes("409")?"Esta competición ya se había añadido.":"No se ha podido añadir la competición.")}finally{setImporting("")}};
 if(loading&&!providers.length)return <p>Cargando proveedores…</p>;
 if(!configured.length)return <div className="empty-state"><h2>Catálogo no configurado</h2><p>Configura un proveedor en el backend para realizar búsquedas online.</p></div>;
 return <section className="catalog-search" aria-labelledby="catalog-title"><h2 id="catalog-title">Buscar competición</h2><form onSubmit={submit}><label>Proveedor<select value={filters.provider??""} onChange={event=>changeProvider(event.target.value)}>{configured.map(item=><option key={item.provider} value={item.provider}>{item.label}</option>)}</select></label><label>Texto<input value={filters.text??""} onChange={event=>setFilters(value=>({...value,text:event.target.value}))}/></label><label>Categoría<select value={filters.category??""} onChange={event=>setFilters(value=>({...value,category:event.target.value as CompetitionCategory|""}))}><option value="">Todas</option>{Object.entries(categoryLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Desde<input type="date" value={filters.start_date??""} onChange={event=>setFilters(value=>({...value,start_date:event.target.value}))}/></label><label>Hasta<input type="date" value={filters.end_date??""} onChange={event=>setFilters(value=>({...value,end_date:event.target.value}))}/></label><label>Localización<input value={filters.location??""} onChange={event=>setFilters(value=>({...value,location:event.target.value}))}/></label><button className="button button--primary" disabled={loading}>{loading?"Buscando…":"Buscar"}</button></form>{error&&<p role="alert" className="error-banner">{error}</p>}{(structured?.length===0||web?.length===0)&&<p>No se han encontrado resultados. Prueba con otro nombre, una zona más amplia o menos filtros.</p>}
 {structured?.map(item=><article className="catalog-result" key={`${item.provider}-${item.external_id}`}><div><h3>{item.name}</h3><p>{item.start_date} · {[item.city,item.region,item.country].filter(Boolean).join(", ")||"Ubicación no disponible"}</p><p>{item.category?categoryLabels[item.category]:"Categoría no disponible"}{item.event_format?` · ${item.event_format}`:""}</p>{item.segments.length>0&&<p>{item.segments.map(segment=>`${segmentLabels[segment.sport]} ${segment.distance_m/1000} km`).join(" · ")}</p>}<small>Fuente: {providers.find(provider=>provider.provider===item.provider)?.label??item.provider}{item.confidence?` · Confianza ${item.confidence==="high"?"alta":item.confidence==="medium"?"media":"baja"}`:""}</small>{item.source_url&&<p><a href={item.source_url} target="_blank" rel="noopener noreferrer">{item.evidence?.some(source=>source.official&&source.url===item.source_url)?"Fuente oficial":"Fuente web"}</a></p>}</div><button className="button button--primary" disabled={Boolean(importing)} onClick={()=>void importEvent(item)}>{importing===item.external_id?"Añadiendo…":"Añadir como objetivo"}</button></article>)}
 {web?.map(item=><article className="catalog-result" key={item.id}><div><h3>{item.title}</h3><small>{item.source_label} · {item.result_kind==="event_listing"?"Calendario o listado":"Resultado web"}</small>{item.snippet&&<p>{item.snippet}</p>}<div aria-label="Pistas encontradas">{item.hints.possible_date&&<p>Posible fecha: {item.hints.possible_date}</p>}{item.hints.possible_location&&<p>Posible lugar: {item.hints.possible_location}</p>}{item.hints.possible_distance&&<p>Posible distancia: {item.hints.possible_distance}</p>}{item.hints.possible_category&&<p>Posible categoría: {categoryLabels[item.hints.possible_category as CompetitionCategory]??item.hints.possible_category}</p>}</div><a href={item.url} target="_blank" rel="noopener noreferrer">Abrir fuente</a></div>{item.result_kind==="event_candidate"&&<button className="button button--primary" onClick={()=>onManualGoal?.({name:item.title,category:filters.category||undefined,sourceProvider:"tavily",sourceUrl:item.url})}>Añadir como objetivo</button>}</article>)}
 {web&&hasMore&&<button className="button" disabled={loadingMore} onClick={()=>void loadMore()}>{loadingMore?"Cargando más…":"Cargar más resultados"}</button>}{moreError&&<p role="alert" className="error-banner">{moreError}</p>}</section>
}
