import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import type { CalendarItem, CalendarItemVariant } from "./calendarItems";
import { monthGridRange, MonthlyCalendar } from "./MonthlyCalendar";

const item = (id: string, date: string, title: string, variant: CalendarItemVariant, kind: CalendarItem["kind"] = "training"): CalendarItem => ({ id, date, title, variant, kind, sport: variant, subtitle: kind === "competition" ? "Competición · Prioridad A" : "Carrera · 45 min", status: "planned", durationSeconds: 2700, sourceId: id });
const renderMonth = (items: CalendarItem[] = [], extra = {}) => render(<MonthlyCalendar items={items} year={2026} month={7} selectedDate={null} onMonthChange={vi.fn()} onSelectDate={vi.fn()} today="2026-08-28" {...extra} />);

describe("MonthlyCalendar", () => {
  it("builds a Monday-to-Sunday six-week range", () => { expect(monthGridRange(2026, 7)).toEqual({ start: "2026-07-27", end: "2026-09-06" }); });
  it("renders full weekday headings and adjacent days", () => { renderMonth(); expect(screen.getAllByRole("columnheader").map((node) => node.textContent)).toEqual(["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]); expect(screen.getByRole("gridcell", { name: /27 de julio/ })).toHaveClass("monthly-day--outside"); });
  it("places August competitions and training on their dates", () => { renderMonth([item("d", "2026-08-25", "duatlón1", "competition", "competition"), item("r", "2026-08-27", "Carrera suave", "running"), item("10k", "2026-08-29", "10K Villanueva", "competition", "competition")]); expect(screen.getByRole("gridcell", { name: /25 de agosto/ })).toHaveTextContent("duatlón1"); expect(screen.getByRole("gridcell", { name: /27 de agosto/ })).toHaveTextContent("Carrera suave"); expect(screen.getByRole("gridcell", { name: /29 de agosto/ })).toHaveTextContent("10K Villanueva"); });
  it("navigates previous and next month", async () => { const change = vi.fn(); renderMonth([], { onMonthChange: change }); await userEvent.click(screen.getByRole("button", { name: "Mes anterior" })); await userEvent.click(screen.getByRole("button", { name: "Mes siguiente" })); expect(change).toHaveBeenNthCalledWith(1, 2026, 6); expect(change).toHaveBeenNthCalledWith(2, 2026, 8); });
  it("coexists, limits three visible events and exposes all in selected-day detail", () => { const items = [item("c", "2026-08-27", "Competición local", "competition", "competition"), item("r", "2026-08-27", "Carrera", "running"), item("b", "2026-08-27", "Bici", "cycling"), item("s", "2026-08-27", "Natación", "swimming"), item("f", "2026-08-27", "Fuerza", "strength")]; renderMonth(items, { selectedDate: "2026-08-27" }); const day = screen.getByRole("gridcell", { name: /5 eventos/ }); expect(within(day).getAllByTitle(/\./)).toHaveLength(3); expect(day).toHaveTextContent("+2 más"); const detail = screen.getByRole("heading", { name: "27 de agosto de 2026" }).parentElement!; for (const value of ["Competición local", "Carrera", "Bici", "Natación", "Fuerza"]) expect(detail).toHaveTextContent(value); });
  it.each(["running", "cycling", "swimming", "strength", "competition"] as const)("reuses the %s semantic class", (variant) => { renderMonth([item(variant, "2026-08-27", variant, variant, variant === "competition" ? "competition" : "training")]); expect(document.querySelector(`.monthly-event.calendar-item--${variant}`)).toBeVisible(); });
  it("distinguishes today from selection", () => { renderMonth([], { selectedDate: "2026-08-27" }); expect(screen.getByRole("gridcell", { name: /28 de agosto/ })).toHaveClass("monthly-day--today"); expect(screen.getByRole("gridcell", { name: /27 de agosto/ })).toHaveClass("monthly-day--selected"); });
});
