const sports:Record<string,string>={running:"Carrera",run:"Carrera",cycling:"Ciclismo",bike:"Ciclismo",swimming:"Natación",swim:"Natación",strength:"Fuerza",competition:"Competición"};
const sessions:Record<string,string>={RUN_EASY:"Carrera suave",RUN_LONG:"Tirada larga",RUN_TEMPO:"Carrera tempo",RUN_THRESHOLD:"Carrera a umbral",RUN_INTERVAL:"Intervalos de carrera",RUN_RECOVERY:"Carrera de recuperación",BIKE_EASY:"Bici suave",BIKE_ENDURANCE:"Bici de resistencia",BIKE_LONG:"Salida larga en bici",BIKE_TEMPO:"Bici tempo",BIKE_THRESHOLD:"Bici a umbral",BIKE_INTERVAL:"Intervalos en bici",BIKE_RECOVERY:"Bici de recuperación",SWIM_TECHNIQUE:"Técnica de natación",SWIM_EASY:"Natación suave",SWIM_AEROBIC:"Natación aeróbica",SWIM_THRESHOLD:"Natación a umbral",SWIM_INTERVAL:"Series de natación",SWIM_ENDURANCE:"Natación de resistencia",GENERAL_STRENGTH:"Fuerza general",COMPETITION:"Competición",EASY:"Suave",RECOVERY:"Recuperación",ENDURANCE:"Resistencia",TEMPO:"Tempo",THRESHOLD:"Umbral",VO2:"VO₂ máx.",LONG:"Sesión larga",BRICK:"Transición",STRENGTH:"Fuerza",REST:"Descanso"};
const purposes:Record<string,string>={AEROBIC_BASE:"Base aeróbica",ENDURANCE:"Resistencia",LONG_ENDURANCE:"Resistencia larga",TECHNIQUE:"Técnica",TEMPO_DEVELOPMENT:"Desarrollo de tempo",THRESHOLD_DEVELOPMENT:"Desarrollo del umbral",HIGH_INTENSITY:"Alta intensidad",RECOVERY:"Recuperación",GENERAL_STRENGTH:"Fuerza general",COMPETITION:"Competición"};
const intensities:Record<string,string>={EASY:"Suave",MODERATE:"Moderada",HARD:"Alta",EVENT:"Competición"};
export const sportLabel=(value:string)=>sports[value]??value;
export const sessionLabel=(value:string)=>sessions[value]??value.replaceAll("_"," ").toLocaleLowerCase("es-ES");
export const purposeLabel=(value:string)=>purposes[value]??value.replaceAll("_"," ").toLocaleLowerCase("es-ES");
export const intensityLabel=(value:string)=>intensities[value]??value;
export const durationLabel=(seconds:number)=>seconds>=3600?`${Math.floor(seconds/3600)} h ${Math.round(seconds%3600/60)} min`:`${Math.round(seconds/60)} min`;
export const minutesLabel=(minutes:number)=>durationLabel(minutes*60);
export const paceLabel=(seconds:number,unit="/km")=>`${Math.floor(seconds/60)}:${String(Math.round(seconds%60)).padStart(2,"0")} ${unit}`;
export function targetLabel(value:unknown,key=""){
 if(typeof value!=="number")return String(value??"");
 const lower=key.toLowerCase();if(lower.includes("pace")&&lower.includes("100"))return paceLabel(value,"/100 m");if(lower.includes("pace"))return paceLabel(value);if(lower.includes("watt"))return `${Math.round(value)} W`;if(lower.includes("heart")||lower.includes("bpm"))return `${Math.round(value)} ppm`;if(lower.includes("rpe"))return `RPE ${value}`;if(lower.includes("duration")||lower.includes("seconds"))return durationLabel(value);return String(value);
}
export function errorMessage(error:unknown){const text=error instanceof Error?error.message:"";if(text.includes("training_plan_active_conflict"))return "Ya existe otro plan activo para este atleta.";if(text.includes("training_plan_invalid_transition"))return "El estado actual del plan no permite realizar esta acción.";if(text.includes("training_plan_overlap"))return "Ya existe un plan de entrenamiento para parte de este periodo.";if(text.includes("fingerprint"))return "La vista previa ya no coincide con la versión esperada.";if(text.includes("athlete_permission_denied")||text.includes("403"))return "No tienes permisos para realizar esta acción.";if(text.includes("planning_preferences_not_found"))return "Completa o guarda tu disponibilidad antes de generar el plan.";if(text.includes("goal")&&text.includes("invalid"))return "Uno de los objetivos ya no es válido para este atleta.";if(text.includes("blocking")||text.includes("NO_TRAINING_AVAILABILITY"))return "La disponibilidad actual impide construir un plan. Revisa los días y minutos disponibles.";if(text.includes("404"))return "El recurso ya no está disponible.";if(text.includes("422"))return "Revisa objetivos, fechas y disponibilidad; no se pudo construir el plan.";return "No se ha podido completar la operación. Inténtalo de nuevo."}
