import {render,screen,waitFor} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {describe,expect,it,vi} from "vitest";
import type {ApiClient} from "../../services/apiClient";
import type {CompetitionGoal,PlanningPreferences,PlanningPreview,TrainingPlan} from "../../types/planning";
import {PlanGeneratorPage,PlanningPreviewPage} from "./PlanningFlowPages";
import {TrainingPlanPage} from "./TrainingPlanPage";

const preferences:PlanningPreferences={availability_slots:[{weekday:0,available_minutes:90,max_sessions:1}],max_sessions_per_day:1,max_sessions_per_week:5,preferred_rest_days:[6],preferred_long_run_day:5,preferred_long_bike_day:6,strength_sessions_per_week:1};
const goal:CompetitionGoal={id:"goal-a",athlete_profile_id:"athlete-a",name:"Triatlón Valencia",event_date:"2099-06-20",event_start_time:null,timezone:"Europe/Madrid",event_category:"triathlon",event_format:"olympic",priority:"A",segments:[{position:1,sport:"swim",distance_m:1500,label:null,elevation_gain_m:null}],distance_m:null,swim_distance_m:1500,bike_distance_m:40000,run_distance_m:10000,target_finish_time_seconds:null,notes:null,city:"Valencia",region:null,country:"España",source_provider:null,source_external_id:null,source_url:null,source_retrieved_at:null,status:"active",created_by_user_id:"u",created_at:"2026-01-01",updated_at:"2026-01-01"};
const prescription={date:"2099-01-04",discipline:"running",session_type:"RUN_EASY",purpose:"AEROBIC_BASE",intensity:"EASY",priority:"SUPPORT",key_session:false,optional:false,target_duration_minutes:45,target_load:30,phase:"BASE",related_goal_ids:[goal.id]};
const competition={...prescription,date:goal.event_date,discipline:"competition",session_type:"COMPETITION",purpose:"COMPETITION",intensity:"EVENT",priority:"REQUIRED",key_session:true,target_duration_minutes:null,target_load:null};
const workout={buildable:true,definition:{schema_version:1,sport:"running",steps:[{kind:"step" as const,phase:"work",duration:{mode:"time",seconds:2700},target:{metric:"rpe",mode:"absolute_range",minimum:2,maximum:4}}]}};
const preview:PlanningPreview={id:"preview-a",status:"pending",created_at:"2026-01-01",accepted_at:null,accepted_training_plan_id:null,artifact:{plan_start:"2099-01-04",plan_end:"2099-06-20",fingerprint:"a".repeat(64),context_fingerprint:"b".repeat(64),timezone_name:"Europe/Madrid",goals:[{competition_goal_id:goal.id,event_date:goal.event_date,priority:"A",role:"primary",category:"triathlon",event_format:"olympic"}],sessions:[{prescription,workout},{prescription:competition,workout:{buildable:false,definition:null}}],session_plan:{warnings:[],weeks:[{week_start:"2099-01-04",week_end:"2099-01-10",sessions:[prescription],rest_dates:["2099-01-10"],unavailable_dates:[],budget_target_load:40,planned_load:30,warnings:[]},{week_start:"2099-06-15",week_end:"2099-06-21",sessions:[competition],rest_dates:[],unavailable_dates:[],budget_target_load:null,planned_load:null,warnings:[]}]},season_structure:{},weekly_budget_plan:{},algorithm_version:"0.8F.6",configuration_version:"0.8F.6"}};
const base=()=>({competitionGoals:vi.fn().mockResolvedValue([goal]),planningPreferences:vi.fn().mockResolvedValue({id:"p",athlete_profile_id:"athlete-a",version_number:1,created_at:"",preferences}),createPlanningPreview:vi.fn().mockResolvedValue(preview),planningPreview:vi.fn().mockResolvedValue(preview),acceptPlanningPreview:vi.fn().mockResolvedValue({training_plan_id:"plan-a",preview_id:preview.id,status:"draft"})}) as unknown as ApiClient;

describe("planning browser flow",()=>{
 it("renders the snapshotted executable target before its relative FTP context",async()=>{window.history.replaceState({},"",`/calendar/planning/previews/${preview.id}`);const resolved={...workout,definition:{...workout.definition,steps:[{kind:"step" as const,phase:"work",duration:{mode:"time",seconds:2700},target:{metric:"power",mode:"percent_reference",reference:"FTP",minimum:.5,maximum:.65,reference_value:250,reference_unit:"watts",resolved_minimum:125,resolved_maximum:163,resolved_unit:"watts"}}]}};const value={...preview,artifact:{...preview.artifact,sessions:[{prescription,workout:resolved},{prescription:competition,workout:{buildable:false,definition:null}}]}};const client=base();client.planningPreview=vi.fn().mockResolvedValue(value);render(<PlanningPreviewPage client={client} canAccept athleteId="athlete-a"/>);await userEvent.click(await screen.findByText(/Ver entrenamiento/));const target=screen.getByText(/Potencia 125–163 W/);expect(target).toHaveTextContent("50–65 % FTP");expect(target).not.toHaveTextContent("0.5–0.65 × FTP")});
 it("uses only the global warning summary and renders the weekly warning once",async()=>{window.history.replaceState({},"",`/calendar/planning/previews/${preview.id}`);const warning={code:"DISCIPLINE_UNDERREPRESENTED",severity:"WARNING" as const,blocking:false,context:{discipline:"cycling"}};const warned={...preview,artifact:{...preview.artifact,session_plan:{...preview.artifact.session_plan,warnings:[warning],weeks:preview.artifact.session_plan.weeks.map((week,index)=>index===0?{...week,warnings:[warning]}:week)}}};const client=base();client.planningPreview=vi.fn().mockResolvedValue(warned);render(<PlanningPreviewPage client={client} canAccept athleteId="athlete-a"/>);expect(await screen.findAllByText(/ciclismo está subrepresentada/)).toHaveLength(2);expect(screen.queryByText(/DISCIPLINE_UNDERREPRESENTED/)).not.toBeInTheDocument()});
 it("preselects the next A goal and sends the visible override once",async()=>{window.history.replaceState({},"","/calendar/planning/new");const client=base();let finish:(value:PlanningPreview)=>void=()=>{};client.createPlanningPreview=vi.fn().mockImplementation(()=>new Promise(value=>{finish=value}));render(<PlanGeneratorPage client={client} canGenerate athleteId="athlete-a" athleteName="Ana"/>);expect(await screen.findByText("Triatlón Valencia")).toBeVisible();expect(screen.getByRole("checkbox",{name:/Triatlón Valencia/})).toBeChecked();await userEvent.click(screen.getByRole("checkbox",{name:/He revisado/}));const button=screen.getByRole("button",{name:"Generar vista previa"});await userEvent.dblClick(button);expect(client.createPlanningPreview).toHaveBeenCalledTimes(1);expect(client.createPlanningPreview).toHaveBeenCalledWith(expect.objectContaining({goal_ids:[goal.id],preferences}));finish(preview);await waitFor(()=>expect(window.location.pathname).toBe(`/calendar/planning/previews/${preview.id}`))});
 it("uses a genuinely empty template after a 404",async()=>{const client=base();client.planningPreferences=vi.fn().mockRejectedValue(new Error("(404) planning_preferences_not_found"));render(<PlanGeneratorPage client={client} canGenerate athleteId="athlete-a"/>);expect(await screen.findByText(/plantilla está vacía/)).toBeVisible();expect(screen.getByLabelText("Minutos Lunes")).toHaveValue(0);expect(screen.getByRole("button",{name:"Generar vista previa"})).toBeDisabled()});
 it("renders sessions, competition, workout and accepts with the fingerprint",async()=>{window.history.replaceState({},"",`/calendar/planning/previews/${preview.id}`);const client=base();render(<PlanningPreviewPage client={client} canAccept athleteId="athlete-a"/>);expect(await screen.findByRole("heading",{name:/Carrera suave/})).toBeVisible();expect(screen.getAllByText("Triatlón Valencia")).toHaveLength(2);expect(screen.getByRole("heading",{name:/Competición/})).toBeVisible();await userEvent.click(screen.getByText(/Ver entrenamiento/));expect(screen.getByText(/RPE 2–4/)).toBeVisible();await userEvent.click(screen.getByRole("button",{name:"Aceptar plan"}));await waitFor(()=>expect(client.acceptPlanningPreview).toHaveBeenCalledTimes(1));expect(client.acceptPlanningPreview).toHaveBeenCalledWith(preview.id,preview.artifact.fingerprint);expect(window.location.pathname).toBe("/calendar/training-plans/plan-a")});
 it("invalidates an old preview when the athlete changes",async()=>{window.history.replaceState({},"",`/calendar/planning/previews/${preview.id}`);const resolvers:Array<(value:PlanningPreview)=>void>=[];const client=base();client.planningPreview=vi.fn().mockImplementation(()=>new Promise(value=>{resolvers.push(value)}));const view=render(<PlanningPreviewPage client={client} canAccept athleteId="athlete-a"/>);await waitFor(()=>expect(resolvers).toHaveLength(1));view.rerender(<PlanningPreviewPage client={client} canAccept athleteId="athlete-b"/>);await waitFor(()=>expect(resolvers).toHaveLength(2));resolvers[0](preview);await new Promise(value=>setTimeout(value,0));expect(screen.queryByRole("button",{name:"Aceptar plan"})).not.toBeInTheDocument()});
 it("shows an accepted plan in read-only week cards",async()=>{window.history.replaceState({},"","/calendar/training-plans/plan-a");const plan:TrainingPlan={id:"plan-a",athlete_profile_id:"athlete-a",title:"Plan inicial",start_date:"2099-01-04",end_date:"2099-01-10",status:"draft",origin:"generated",algorithm_version:"0.8F.6",goals:[{competition_goal_id:goal.id,relationship:"primary"}],sessions:[{id:"s",scheduled_date:prescription.date,sport:"running",title:"Carrera suave",description:null,planned_duration_seconds:2700,workout:workout.definition}]};const client=base();client.trainingPlan=vi.fn().mockResolvedValue(plan);render(<TrainingPlanPage client={client} athleteId="athlete-a"/>);expect(await screen.findByRole("heading",{name:"Plan inicial"})).toBeVisible();expect(screen.getByText(/Borrador/)).toBeVisible();expect(screen.getByText("Carrera suave")).toBeVisible();expect(screen.queryByRole("button",{name:"Activar plan"})).not.toBeInTheDocument()});
 it("activates a draft once and replaces its lifecycle actions",async()=>{window.history.replaceState({},"","/calendar/training-plans/plan-a");const plan:TrainingPlan={id:"plan-a",athlete_profile_id:"athlete-a",title:"Plan inicial",start_date:"2099-01-04",end_date:"2099-01-10",status:"draft",origin:"ai",algorithm_version:"0.8F.6",goals:[],sessions:[]};let resolve!:(value:TrainingPlan)=>void;const client=base();client.trainingPlan=vi.fn().mockResolvedValue(plan);client.activateTrainingPlan=vi.fn().mockReturnValue(new Promise(done=>{resolve=done}));render(<TrainingPlanPage client={client} athleteId="athlete-a" canManage/>);const activate=await screen.findByRole("button",{name:"Activar plan"});await userEvent.dblClick(activate);expect(client.activateTrainingPlan).toHaveBeenCalledTimes(1);expect(screen.getByRole("button",{name:/Activando/})).toBeDisabled();resolve({...plan,status:"active"});expect(await screen.findByText(/Estado: Activo/)).toBeVisible();expect(screen.getByRole("button",{name:"Marcar como completado"})).toBeEnabled();expect(screen.queryByRole("button",{name:"Activar plan"})).not.toBeInTheDocument()});
 it("confirms archive and restores controls after a controlled conflict",async()=>{window.history.replaceState({},"","/calendar/training-plans/plan-a");const plan:TrainingPlan={id:"plan-a",athlete_profile_id:"athlete-a",title:"Plan",start_date:"2099-01-04",end_date:"2099-01-10",status:"active",origin:"ai",algorithm_version:"0.8F.6",goals:[],sessions:[]};vi.spyOn(window,"confirm").mockReturnValue(true);const client=base();client.trainingPlan=vi.fn().mockResolvedValue(plan);client.archiveTrainingPlan=vi.fn().mockRejectedValue(new Error('(409) {"code":"training_plan_invalid_transition"}'));render(<TrainingPlanPage client={client} athleteId="athlete-a" canManage/>);await userEvent.click(await screen.findByRole("button",{name:"Archivar"}));expect(window.confirm).toHaveBeenCalled();expect(await screen.findByRole("alert")).toHaveTextContent("El estado actual del plan");expect(screen.getByRole("button",{name:"Archivar"})).toBeEnabled()});
});

describe("planning overlap UX",()=>{
 it("keeps the preview visible when accept finds an overlapping plan",async()=>{window.history.replaceState({},"",`/calendar/planning/previews/${preview.id}`);const client=base();client.acceptPlanningPreview=vi.fn().mockRejectedValue(new Error('(409) {"code":"training_plan_overlap","existing_training_plan_id":"plan-old"}'));render(<PlanningPreviewPage client={client} canAccept athleteId="athlete-a"/>);await screen.findByRole("button",{name:"Aceptar plan"});await userEvent.click(screen.getByRole("button",{name:"Aceptar plan"}));expect(await screen.findByRole("alert")).toHaveTextContent("Ya existe un plan de entrenamiento para parte de este periodo.");expect(screen.getByRole("heading",{name:"Revisa tu plan"})).toBeVisible();expect(window.location.pathname).toContain(preview.id)});
 it("restores acceptance after a pending 409 without duplicate requests",async()=>{window.history.replaceState({},"",`/calendar/planning/previews/${preview.id}`);let reject!:(reason:Error)=>void;const client=base();client.acceptPlanningPreview=vi.fn().mockReturnValue(new Promise((_,fail)=>{reject=fail}));render(<PlanningPreviewPage client={client} canAccept athleteId="athlete-a"/>);const button=await screen.findByRole("button",{name:"Aceptar plan"});await userEvent.dblClick(button);expect(client.acceptPlanningPreview).toHaveBeenCalledTimes(1);expect(screen.getByRole("button",{name:/Aceptando/})).toBeDisabled();reject(new Error('(409) {"code":"training_plan_overlap"}'));expect(await screen.findByRole("alert")).toHaveTextContent("Ya existe un plan de entrenamiento para parte de este periodo.");expect(screen.getByRole("button",{name:"Aceptar plan"})).toBeEnabled()});
});
